namespace :db do
  desc "Fill database with jeans"
  task populate: :environment do
    make_items
  end
end

def make_items

#3sixteen SL-100x--------------------------------------
	Item.create!(name: "SL-100x",
				   brand: "3sixteen",
				   tag_size: 28,
				   waist: 29,
				   front_rise: 10.3,
				   thigh: 10.7,
				   knee: 8.2,
				   leg_opening: 7.3,
				   color: "Indigo",
				   fabric_origin: "Kuroki Mills",
				   made_in: "USA",
				   denim_weight: 14.5,
				   inseam: 37,
				   sanforized: true,
				   stretch: false,
				   selvedge: true,
				   price: "215.00",
				   link: "http://www.selfedge.com/shop/index.php?main_page=product_info&cPath=82&products_id=438")

	Item.create!(name: "SL-100x",
				   brand: "3sixteen",
				   tag_size: 29,
				   waist: 30,
				   front_rise: 10.4,
				   thigh: 11.0,
				   knee: 8.3,
				   leg_opening: 7.5,
				   inseam: 37,
				   color: "Indigo",
				   fabric_origin: "Kuroki Mills",
				   made_in: "USA",
				   denim_weight: 14.5,
				   sanforized: true,
				   stretch: false,
				   selvedge: true,
				   price: "215.00",
				   link: "http://www.selfedge.com/shop/index.php?main_page=product_info&cPath=82&products_id=438")

	Item.create!(name: "SL-100x",
				   brand: "3sixteen",
				   tag_size: 30,
				   waist: 31,
				   front_rise: 10.8,
				   thigh: 11.2,
				   knee: 8.3,
				   leg_opening: 7.7,
				   inseam: 37,
				   color: "Indigo",
				   fabric_origin: "Kuroki Mills",
				   made_in: "USA",
				   denim_weight: 14.5,
				   sanforized: true,
				   stretch: false,
				   selvedge: true,
				   price: "215.00",
				   link: "http://www.selfedge.com/shop/index.php?main_page=product_info&cPath=82&products_id=438")

	Item.create!(name: "SL-100x",
				   brand: "3sixteen",
				   tag_size: 31,
				   waist: 32,
				   front_rise: 11,
				   thigh: 11.3,
				   knee: 8.4,
				   leg_opening: 7.8,
				   inseam: 37,
				   color: "Indigo",
				   fabric_origin: "Kuroki Mills",
				   made_in: "USA",
				   denim_weight: 14.5,
				   sanforized: true,
				   stretch: false,
				   selvedge: true,
				   price: "215.00",
				   link: "http://www.selfedge.com/shop/index.php?main_page=product_info&cPath=82&products_id=438")

	Item.create!(name: "SL-100x",
				   brand: "3sixteen",
				   tag_size: 32,
				   waist: 33,
				   front_rise: 11.1,
				   thigh: 11.7,
				   knee: 8.7,
				   leg_opening: 7.9,
				   inseam: 37,
				   color: "Indigo",
				   denim_weight: 14.5,
				   fabric_origin: "Kuroki Mills",
				   made_in: "USA",
				   sanforized: true,
				   stretch: false,
				   selvedge: true,
				   price: "215.00",
				   link: "http://www.selfedge.com/shop/index.php?main_page=product_info&cPath=82&products_id=438")

	Item.create!(name: "SL-100x",
				   brand: "3sixteen",
				   tag_size: 33,
				   waist: 34,
				   front_rise: 11.3,
				   thigh: 12,
				   knee: 8.8,
				   leg_opening: 8,
				   inseam: 37,
				   color: "Indigo",
				   fabric_origin: "Kuroki Mills",
				   made_in: "USA",
				   denim_weight: 14.5,
				   sanforized: true,
				   stretch: false,
				   selvedge: true,
				   price: "215.00",
				   link: "http://www.selfedge.com/shop/index.php?main_page=product_info&cPath=82&products_id=438")
	
	Item.create!(name: "SL-100x",
				   brand: "3sixteen",
				   tag_size: 34,
				   waist: 35,
				   front_rise: 11.7,
				   thigh: 12.3,
				   knee: 9.1,
				   leg_opening: 8.2,
				   inseam: 37,
				   color: "Indigo",
				   fabric_origin: "Kuroki Mills",
				   made_in: "USA",
				   denim_weight: 14.5,
				   sanforized: true,
				   stretch: false,
				   selvedge: true,
				   price: "215.00",
				   link: "http://www.selfedge.com/shop/index.php?main_page=product_info&cPath=82&products_id=438")

	Item.create!(name: "SL-100x",
				   brand: "3sixteen",
				   tag_size: 36,
				   waist: 37,
				   front_rise: 12.1,
				   thigh: 12.7,
				   knee: 9.5,
				   leg_opening: 8.6,
				   inseam: 37,
				   color: "Indigo",
				   fabric_origin: "Kuroki Mills",
				   made_in: "USA",
				   denim_weight: 14.5,
				   sanforized: true,
				   stretch: false,
				   selvedge: true,
				   price: "215.00",
				   link: "http://www.selfedge.com/shop/index.php?main_page=product_info&cPath=82&products_id=438")

	Item.create!(name: "SL-100x",
				   brand: "3sixteen",
				   tag_size: 38,
				   waist: 39,
				   front_rise: 12.3,
				   thigh: 13,
				   knee: 9.5,
				   leg_opening: 9,
				   inseam: 37,
				   color: "Indigo",
				   fabric_origin: "Kuroki Mills",
				   made_in: "USA",
				   denim_weight: 14.5,
				   sanforized: true,
				   stretch: false,
				   selvedge: true,
				   price: "215.00",
				   link: "http://www.selfedge.com/shop/index.php?main_page=product_info&cPath=82&products_id=438")

	Item.create!(name: "SL-100x",
				   brand: "3sixteen",
				   tag_size: 40,
				   waist: 41,
				   front_rise: 12.5,
				   thigh: 14,
				   knee: 9.8,
				   leg_opening: 9.1,
				   inseam: 37,
				   color: "Indigo",
				   fabric_origin: "Kuroki Mills",
				   made_in: "USA",
				   denim_weight: 14.5,
				   sanforized: true,
				   stretch: false,
				   selvedge: true,
				   price: "215.00",
				   link: "http://www.selfedge.com/shop/index.php?main_page=product_info&cPath=82&products_id=438")

#3sixteen ST-100x-----------------------------------------------

	Item.create!(name: "ST-100x",
				   brand: "3sixteen",
					tag_size: 28,
					waist: 28.5,
					front_rise: 10.15,
					thigh: 10.15,
					knee: 7.25,
					leg_opening: 7,
					inseam: 37,
				   color: "Indigo",
				   fabric_origin: "Kuroki Mills",
				   made_in: "USA",
				   denim_weight: 14.5,
				   sanforized: true,
				   stretch: false,
				   selvedge: true,
				   price: "215.00",
				   link: "http://www.blueowl.us/product/3sixteen-slim-tapered-145oz-selvedge-denim-in-indigo-model-st-100x/")

	Item.create!(name: "ST-100x",
				   brand: "3sixteen",
					tag_size: 29,
					waist: 29.5,
					front_rise: 10.25,
					thigh: 10.5,
					knee: 7.5,
					leg_opening: 7.15,
					inseam: 37,
				   color: "Indigo",
				   fabric_origin: "Kuroki Mills",
				   made_in: "USA",
				   denim_weight: 14.5,
				   sanforized: true,
				   stretch: false,
				   selvedge: true,
				   price: "215.00",
				   link: "http://www.blueowl.us/product/3sixteen-slim-tapered-145oz-selvedge-denim-in-indigo-model-st-100x/")

	Item.create!(name: "ST-100x",
				   brand: "3sixteen",
					tag_size: 30,
					waist: 30.5,
					front_rise: 10.5,
					thigh: 11,
					knee: 7.75,
					leg_opening: 7.25,
					inseam: 37,
				   color: "Indigo",
				   fabric_origin: "Kuroki Mills",
				   made_in: "USA",
				   denim_weight: 14.5,
				   sanforized: true,
				   stretch: false,
				   selvedge: true,
				   price: "215.00",
				   link: "http://www.blueowl.us/product/3sixteen-slim-tapered-145oz-selvedge-denim-in-indigo-model-st-100x/")

	Item.create!(name: "ST-100x",
				   brand: "3sixteen",
					tag_size: 31,
					waist: 31.5,
					front_rise: 10.75,
					thigh: 11.25,
					knee: 8,
					leg_opening: 7.4,
					inseam: 37,
				   color: "Indigo",
				   fabric_origin: "Kuroki Mills",
				   made_in: "USA",
				   denim_weight: 14.5,
				   sanforized: true,
				   stretch: false,
				   selvedge: true,
				   price: "215.00",
				   link: "http://www.blueowl.us/product/3sixteen-slim-tapered-145oz-selvedge-denim-in-indigo-model-st-100x/")

	Item.create!(name: "ST-100x",
				   brand: "3sixteen",
					tag_size: 32,
					waist: 32.5,
					front_rise: 10.75,
					thigh: 11.5,
					knee: 8,
					leg_opening: 7.5,
					inseam: 37,
				   color: "Indigo",
				   fabric_origin: "Kuroki Mills",
				   made_in: "USA",
				   denim_weight: 14.5,
				   sanforized: true,
				   stretch: false,
				   selvedge: true,
				   price: "215.00",
				   link: "http://www.blueowl.us/product/3sixteen-slim-tapered-145oz-selvedge-denim-in-indigo-model-st-100x/")

	Item.create!(name: "ST-100x",
				   brand: "3sixteen",
					tag_size: 33,
					waist: 33.5,
					front_rise: 10.75,
					thigh: 11.5,
					knee: 8,
					leg_opening: 7.65,
					inseam: 37,
				   color: "Indigo",
				   fabric_origin: "Kuroki Mills",
				   made_in: "USA",
				   denim_weight: 14.5,
				   sanforized: true,
				   stretch: false,
				   selvedge: true,
				   price: "215.00",
				   link: "http://www.blueowl.us/product/3sixteen-slim-tapered-145oz-selvedge-denim-in-indigo-model-st-100x/")

	Item.create!(name: "ST-100x",
				   brand: "3sixteen",
					tag_size: 34,
					waist: 34.5,
					front_rise: 10.75,
					thigh: 12,
					knee: 8.25,
					leg_opening: 7.75,
					inseam: 37,
				   color: "Indigo",
				   fabric_origin: "Kuroki Mills",
				   made_in: "USA",
				   denim_weight: 14.5,
				   sanforized: true,
				   stretch: false,
				   selvedge: true,
				   price: "215.00",
				   link: "http://www.blueowl.us/product/3sixteen-slim-tapered-145oz-selvedge-denim-in-indigo-model-st-100x/")

	Item.create!(name: "ST-100x",
				   brand: "3sixteen",
					tag_size: 36,
					waist: 36.75,
					front_rise: 11,
					thigh: 12.5,
					knee: 8.7,
					leg_opening: 8,
					inseam: 37,
				   color: "Indigo",
				   fabric_origin: "Kuroki Mills",
				   made_in: "USA",
				   denim_weight: 14.5,
				   sanforized: true,
				   stretch: false,
				   selvedge: true,
				   price: "215.00",
				   link: "http://www.blueowl.us/product/3sixteen-slim-tapered-145oz-selvedge-denim-in-indigo-model-st-100x/")


#Rogue Territory Stanton-----------------------------------------
	Item.create!(name: "Stanton 14.5oz",
				   brand: "Rogue Territory",
				   tag_size: 26,
				   waist: 28.5,
				   front_rise: 9.75,
				   thigh: 10.5,
				   knee: 7,
				   leg_opening: 6.5,
				   inseam: 36,
				   color: "Indigo",
				   fabric_origin: "Nihon Menpu Mills",
				   made_in: "USA",
				   denim_weight: 14.5,
				   sanforized: true,
				   stretch: false,
				   selvedge: true,
				   price: "210.00",
				   link: "http://www.selfedge.com/shop/index.php?main_page=product_info&cPath=82&products_id=438")

	Item.create!(name: "Stanton 14.5oz",
				   brand: "Rogue Territory",
				   tag_size: 27,
				   waist: 29.5,
				   front_rise: 9.75,
				   thigh: 11,
				   knee: 7.25,
				   leg_opening: 6.75,
				   inseam: 36,
				   color: "Indigo",
				   fabric_origin: "Nihon Menpu Mills",
				   made_in: "USA",
				   denim_weight: 14.5,
				   sanforized: true,
				   stretch: false,
				   selvedge: true,
				   price: "210.00",
				   link: "http://www.selfedge.com/shop/index.php?main_page=product_info&cPath=82&products_id=438")

	Item.create!(name: "Stanton 14.5oz",
				   brand: "Rogue Territory",
				   tag_size: 28,
				   waist: 30.5,
				   front_rise: 10,
				   thigh: 11.25,
				   knee: 7.5,
				   leg_opening: 7,
				   inseam: 36,
				   color: "Indigo",
				   fabric_origin: "Nihon Menpu Mills",
				   made_in: "USA",
				   denim_weight: 14.5,
				   sanforized: true,
				   stretch: false,
				   selvedge: true,
				   price: "210.00",
				   link: "http://www.selfedge.com/shop/index.php?main_page=product_info&cPath=82&products_id=438")

	Item.create!(name: "Stanton 14.5oz",
				   brand: "Rogue Territory",
				   tag_size: 29,
				   waist: 31.5,
				   front_rise: 10.25,
				   thigh: 11.5,
				   knee: 8,
				   leg_opening: 7.5,
				   inseam: 36,
				   color: "Indigo",
				   fabric_origin: "Nihon Menpu Mills",
				   made_in: "USA",
				   denim_weight: 14.5,
				   sanforized: true,
				   stretch: false,
				   selvedge: true,
				   price: "210.00",
				   link: "http://www.selfedge.com/shop/index.php?main_page=product_info&cPath=82&products_id=438")

	Item.create!(name: "Stanton 14.5oz",
				   brand: "Rogue Territory",
				   tag_size: 30,
				   waist: 32.5,
				   front_rise: 10.25,
				   thigh: 11.75,
				   knee: 8.25,
				   leg_opening: 7.75,
				   inseam: 36,
				   color: "Indigo",
				   fabric_origin: "Nihon Menpu Mills",
				   made_in: "USA",
				   denim_weight: 14.5,
				   sanforized: true,
				   stretch: false,
				   selvedge: true,
				   price: "210.00",
				   link: "http://www.selfedge.com/shop/index.php?main_page=product_info&cPath=82&products_id=438")

	Item.create!(name: "Stanton 14.5oz",
				   brand: "Rogue Territory",
				   tag_size: 31,
				   waist: 33.5,
				   front_rise: 10.5,
				   thigh: 12,
				   knee: 8.5,
				   leg_opening: 8,
				   inseam: 36,
				   color: "Indigo",
				   fabric_origin: "Nihon Menpu Mills",
				   made_in: "USA",
				   denim_weight: 14.5,
				   sanforized: true,
				   stretch: false,
				   selvedge: true,
				   price: "210.00",
				   link: "http://www.selfedge.com/shop/index.php?main_page=product_info&cPath=82&products_id=438")

	Item.create!(name: "Stanton 14.5oz",
				   brand: "Rogue Territory",
				   tag_size: 32,
				   waist: 34.5,
				   front_rise: 10.5,
				   thigh: 12.5,
				   knee: 8.75,
				   leg_opening: 8.25,
				   inseam: 36,
				   color: "Indigo",
				   fabric_origin: "Nihon Menpu Mills",
				   made_in: "USA",
				   denim_weight: 14.5,
				   sanforized: true,
				   stretch: false,
				   selvedge: true,
				   price: "210.00",
				   link: "http://www.selfedge.com/shop/index.php?main_page=product_info&cPath=82&products_id=438")

	Item.create!(name: "Stanton 14.5oz",
				   brand: "Rogue Territory",
				   tag_size: 33,
				   waist: 35.5,
				   front_rise: 10.75,
				   thigh: 12.75,
				   knee: 9,
				   leg_opening: 8.5,
				   inseam: 36,
				   color: "Indigo",
				   fabric_origin: "Nihon Menpu Mills",
				   made_in: "USA",
				   denim_weight: 14.5,
				   sanforized: true,
				   stretch: false,
				   selvedge: true,
				   price: "210.00",
				   link: "http://www.selfedge.com/shop/index.php?main_page=product_info&cPath=82&products_id=438")

	Item.create!(name: "Stanton 14.5oz",
				   brand: "Rogue Territory",
				   tag_size: 34,
				   waist: 36.5,
				   front_rise: 11,
				   thigh: 13,
				   knee: 9.25,
				   leg_opening: 8.75,
				   inseam: 36,
				   color: "Indigo",
				   fabric_origin: "Nihon Menpu Mills",
				   made_in: "USA",
				   denim_weight: 14.5,
				   sanforized: true,
				   stretch: false,
				   selvedge: true,
				   price: "210.00",
				   link: "http://www.selfedge.com/shop/index.php?main_page=product_info&cPath=82&products_id=438")

	Item.create!(name: "Stanton 14.5oz",
				   brand: "Rogue Territory",
				   tag_size: 36,
				   waist: 38.5,
				   front_rise: 11.25,
				   thigh: 13.5,
				   knee: 9.75,
				   leg_opening: 9,
				   inseam: 36,
				   color: "Indigo",
				   fabric_origin: "Nihon Menpu Mills",
				   made_in: "USA",
				   denim_weight: 14.5,
				   sanforized: true,
				   stretch: false,
				   selvedge: true,
				   price: "210.00",
				   link: "http://www.selfedge.com/shop/index.php?main_page=product_info&cPath=82&products_id=438")

	Item.create!(name: "Stanton 14.5oz",
				   brand: "Rogue Territory",
				   tag_size: 38,
				   waist: 40.5,
				   front_rise: 11.25,
				   thigh: 15,
				   knee: 10,
				   leg_opening: 9.25,
				   inseam: 36,
				   color: "Indigo",
				   fabric_origin: "Nihon Menpu Mills",
				   made_in: "USA",
				   denim_weight: 14.5,
				   sanforized: true,
				   stretch: false,
				   selvedge: true,
				   price: "210.00",
				   link: "http://www.selfedge.com/shop/index.php?main_page=product_info&cPath=82&products_id=438")

#N&F x Big John x Rockin' Jelly Bean----------------------------
	Item.create!(name: "N&F x Big John x Rockin' Jelly Bean Collaboration",
				   brand: "Naked & Famous x Big John",
				   tag_size: 28,
				   waist: 28.5,
				   front_rise: 9.25,
				   thigh: 9.75,
				   knee: 7.5,
				   leg_opening: 6,
				   inseam: 34,
				   color: "Light Indigo",
				   fabric_origin: "Big John RURI",
				   made_in: "Japan",
				   denim_weight: 14.5,
				   sanforized: true,
				   stretch: false,
				   selvedge: true,
				   price: "265.00",
				   link: "http://www.blueowl.us/product/naked-and-famous-x-big-john-x-rockin-jelly-bean-super-skinny-guy-145oz-ruri-denim-collaboration/")

	Item.create!(name: "N&F x Big John x Rockin' Jelly Bean Collaboration",
				   brand: "Naked & Famous x Big John",
				   tag_size: 29,
				   waist: 29.5,
				   front_rise: 9.25,
				   thigh: 10.25,
				   knee: 7.75,
				   leg_opening: 6.5,
				   inseam: 34,
				   color: "Light Indigo",
				   fabric_origin: "Big John RURI",
				   made_in: "Japan",
				   denim_weight: 14.5,
				   sanforized: true,
				   stretch: false,
				   selvedge: true,
				   price: "265.00",
				   link: "http://www.blueowl.us/product/naked-and-famous-x-big-john-x-rockin-jelly-bean-super-skinny-guy-145oz-ruri-denim-collaboration/")

	Item.create!(name: "N&F x Big John x Rockin' Jelly Bean Collaboration",
				   brand: "Naked & Famous x Big John",
				   tag_size: 30,
				   waist: 30.5,
				   front_rise: 9.5,
				   thigh: 10.5,
				   knee: 8,
				   leg_opening: 6.5,
				   inseam: 34,
				   color: "Light Indigo",
				   fabric_origin: "Big John RURI",
				   made_in: "Japan",
				   denim_weight: 14.5,
				   sanforized: true,
				   stretch: false,
				   selvedge: true,
				   price: "265.00",
				   link: "http://www.blueowl.us/product/naked-and-famous-x-big-john-x-rockin-jelly-bean-super-skinny-guy-145oz-ruri-denim-collaboration/")

	Item.create!(name: "N&F x Big John x Rockin' Jelly Bean Collaboration",
				   brand: "Naked & Famous x Big John",
				   tag_size: 31,
				   waist: 31.5,
				   front_rise: 9.5,
				   thigh: 10.5,
				   knee: 8.15,
				   leg_opening: 6.75,
				   inseam: 34,
				   color: "Light Indigo",
				   fabric_origin: "Big John RURI",
				   made_in: "Japan",
				   denim_weight: 14.5,
				   sanforized: true,
				   stretch: false,
				   selvedge: true,
				   price: "265.00",
				   link: "http://www.blueowl.us/product/naked-and-famous-x-big-john-x-rockin-jelly-bean-super-skinny-guy-145oz-ruri-denim-collaboration/")

	Item.create!(name: "N&F x Big John x Rockin' Jelly Bean Collaboration",
				   brand: "Naked & Famous x Big John",
				   tag_size: 32,
				   waist: 32.5,
				   front_rise: 9.75,
				   thigh: 10.75,
				   knee: 8.25,
				   leg_opening: 7,
				   inseam: 34,
				   color: "Light Indigo",
				   fabric_origin: "Big John RURI",
				   made_in: "Japan",
				   denim_weight: 14.5,
				   sanforized: true,
				   stretch: false,
				   selvedge: true,
				   price: "265.00",
				   link: "http://www.blueowl.us/product/naked-and-famous-x-big-john-x-rockin-jelly-bean-super-skinny-guy-145oz-ruri-denim-collaboration/")

	Item.create!(name: "N&F x Big John x Rockin' Jelly Bean Collaboration",
				   brand: "Naked & Famous x Big John",
				   tag_size: 33,
				   waist: 33.5,
				   front_rise: 9.75,
				   thigh: 11.15,
				   knee: 8.5,
				   leg_opening: 7,
				   inseam: 34,
				   color: "Light Indigo",
				   fabric_origin: "Big John RURI",
				   made_in: "Japan",
				   denim_weight: 14.5,
				   sanforized: true,
				   stretch: false,
				   selvedge: true,
				   price: "265.00",
				   link: "http://www.blueowl.us/product/naked-and-famous-x-big-john-x-rockin-jelly-bean-super-skinny-guy-145oz-ruri-denim-collaboration/")

	Item.create!(name: "N&F x Big John x Rockin' Jelly Bean Collaboration",
				   brand: "Naked & Famous x Big John",
				   tag_size: 34,
				   waist: 34.5,
				   front_rise: 9.75,
				   thigh: 11.5,
				   knee: 8.75,
				   leg_opening: 7.25,
				   inseam: 34,
				   color: "Light Indigo",
				   fabric_origin: "Big John RURI",
				   made_in: "Japan",
				   denim_weight: 14.5,
				   sanforized: true,
				   stretch: false,
				   selvedge: true,
				   price: "265.00",
				   link: "http://www.blueowl.us/product/naked-and-famous-x-big-john-x-rockin-jelly-bean-super-skinny-guy-145oz-ruri-denim-collaboration/")

	Item.create!(name: "N&F x Big John x Rockin' Jelly Bean Collaboration",
				   brand: "Naked & Famous x Big John",
				   tag_size: 36,
				   waist: 36,
				   front_rise: 10,
				   thigh: 12,
				   knee: 9.25,
				   leg_opening: 7.75,
				   inseam: 34,
				   color: "Light Indigo",
				   fabric_origin: "China",
				   made_in: "China",
				   denim_weight: 14.5,
				   sanforized: true,
				   stretch: false,
				   selvedge: true,
				   price: "265.00",
				   link: "http://www.blueowl.us/product/naked-and-famous-x-big-john-x-rockin-jelly-bean-super-skinny-guy-145oz-ruri-denim-collaboration/")

#APC New Standard
	Item.create!(name: "New Standard",
				   brand: "APC",
				   tag_size: 25,
				   waist: 26,
				   front_rise: 9.5,
				   thigh: 9.5,
				   knee: 7,
				   leg_opening: 6.5,
				   inseam: 33.5,
				   color: "Indigo",
				   fabric_origin: "China",
				   made_in: "China",
				   denim_weight: 12,
				   sanforized: true,
				   stretch: true,
				   selvedge: true,
				   price: "185.00",
				   link: "http://www.contextclothing.com/item.php?id=6")

	Item.create!(name: "New Standard",
				   brand: "APC",
				   tag_size: 26,
				   waist: 27,
				   front_rise: 10,
				   thigh: 10,
				   knee: 7.5,
				   leg_opening: 7,
				   inseam: 33.5,
				   color: "Indigo",
				   fabric_origin: "China",
				   made_in: "China",
				   denim_weight: 12,
				   sanforized: true,
				   stretch: true,
				   selvedge: true,
				   price: "185.00",
				   link: "http://www.contextclothing.com/item.php?id=6")

	Item.create!(name: "New Standard",
				   brand: "APC",
				   tag_size: 27,
				   waist: 28,
				   front_rise: 10,
				   thigh: 10,
				   knee: 7.5,
				   leg_opening: 7,
				   inseam: 33.5,
				   color: "Indigo",
				   fabric_origin: "China",
				   made_in: "China",
				   denim_weight: 12,
				   sanforized: true,
				   stretch: true,
				   selvedge: true,
				   price: "185.00",
				   link: "http://www.contextclothing.com/item.php?id=6")

	Item.create!(name: "New Standard",
				   brand: "APC",
				   tag_size: 28,
				   waist: 29,
				   front_rise: 9.5,
				   thigh: 10,
				   knee: 7.5,
				   leg_opening: 7,
				   inseam: 33.5,
				   color: "Indigo",
				   fabric_origin: "China",
				   made_in: "China",
				   denim_weight: 12,
				   sanforized: true,
				   stretch: true,
				   selvedge: true,
				   price: "185.00",
				   link: "http://www.contextclothing.com/item.php?id=6")

	Item.create!(name: "New Standard",
				   brand: "APC",
				   tag_size: 29,
				   waist: 30,
				   front_rise: 10,
				   thigh: 11,
				   knee: 8,
				   leg_opening: 7.5,
				   inseam: 33.5,
				   color: "Indigo",
				   fabric_origin: "China",
				   made_in: "China",
				   denim_weight: 12,
				   sanforized: true,
				   stretch: true,
				   selvedge: true,
				   price: "185.00",
				   link: "http://www.contextclothing.com/item.php?id=6")

	Item.create!(name: "New Standard",
				   brand: "APC",
				   tag_size: 30,
				   waist: 31,
				   front_rise: 10,
				   thigh: 11,
				   knee: 8,
				   leg_opening: 7.5,
				   inseam: 34.5,
				   color: "Indigo",
				   fabric_origin: "China",
				   made_in: "China",
				   denim_weight: 12,
				   sanforized: true,
				   stretch: true,
				   selvedge: true,
				   price: "185.00",
				   link: "http://www.contextclothing.com/item.php?id=6")

	Item.create!(name: "New Standard",
				   brand: "APC",
				   tag_size: 31,
				   waist: 32,
				   front_rise: 10,
				   thigh: 11.5,
				   knee: 8.5,
				   leg_opening: 8,
				   inseam: 35.5,
				   color: "Indigo",
				   fabric_origin: "China",
				   made_in: "China",
				   denim_weight: 12,
				   sanforized: true,
				   stretch: true,
				   selvedge: true,
				   price: "185.00",
				   link: "http://www.contextclothing.com/item.php?id=6")

	Item.create!(name: "New Standard",
				   brand: "APC",
				   tag_size: 32,
				   waist: 33,
				   front_rise: 10,
				   thigh: 11.5,
				   knee: 8.5,
				   leg_opening: 8,
				   inseam: 35.5,
				   color: "Indigo",
				   fabric_origin: "China",
				   made_in: "China",
				   denim_weight: 12,
				   sanforized: true,
				   stretch: true,
				   selvedge: true,
				   price: "185.00",
				   link: "http://www.contextclothing.com/item.php?id=6")

	Item.create!(name: "New Standard",
				   brand: "APC",
				   tag_size: 33,
				   waist: 34,
				   front_rise: 10.5,
				   thigh: 12,
				   knee: 9,
				   leg_opening: 8.5,
				   inseam: 36,
				   color: "Indigo",
				   fabric_origin: "China",
				   made_in: "China",
				   denim_weight: 12,
				   sanforized: true,
				   stretch: true,
				   selvedge: true,
				   price: "185.00",
				   link: "http://www.contextclothing.com/item.php?id=6")

	Item.create!(name: "New Standard",
				   brand: "APC",
				   tag_size: 34,
				   waist: 35,
				   front_rise: 10.5,
				   thigh: 12,
				   knee: 9,
				   leg_opening: 8.5,
				   inseam: 36,
				   color: "Indigo",
				   fabric_origin: "China",
				   made_in: "China",
				   denim_weight: 12,
				   sanforized: true,
				   stretch: true,
				   selvedge: true,
				   price: "185.00",
				   link: "http://www.contextclothing.com/item.php?id=6")

	Item.create!(name: "New Standard",
				   brand: "APC",
				   tag_size: 35,
				   waist: 36,
				   front_rise: 11,
				   thigh: 12.5,
				   knee: 9.5,
				   leg_opening: 9,
				   inseam: 36,
				   color: "Indigo",
				   fabric_origin: "China",
				   made_in: "China",
				   denim_weight: 12,
				   sanforized: true,
				   stretch: true,
				   selvedge: true,
				   price: "185.00",
				   link: "http://www.contextclothing.com/item.php?id=6")

	Item.create!(name: "New Standard",
				   brand: "APC",
				   tag_size: 36,
				   waist: 37,
				   front_rise: 11,
				   thigh: 12.5,
				   knee: 9.5,
				   leg_opening: 9,
				   inseam: 36.5,
				   color: "Indigo",
				   fabric_origin: "China",
				   made_in: "China",
				   denim_weight: 12,
				   sanforized: true,
				   stretch: true,
				   selvedge: true,
				   price: "185.00",
				   link: "http://www.contextclothing.com/item.php?id=6")

#APC Petit Standard----------------------------------
	Item.create!(name: "Petit Standard",
				   brand: "APC",
				   tag_size: 25,
				   waist: 26,
				   front_rise: 9,
				   thigh: 9.5,
				   knee: 6.5,
				   leg_opening: 6,
				   inseam: 33,
				   color: "Indigo",
				   fabric_origin: "China",
				   made_in: "China",
				   denim_weight: 12,
				   sanforized: true,
				   stretch: true,
				   selvedge: true,
				   price: "185.00",
				   link: "http://www.contextclothing.com/item.php?id=665")

	Item.create!(name: "Petit Standard",
				   brand: "APC",
				   tag_size: 26,
				   waist: 27,
				   front_rise: 9,
				   thigh: 10,
				   knee: 6.5,
				   leg_opening: 6,
				   inseam: 33,
				   color: "Indigo",
				   fabric_origin: "China",
				   made_in: "China",
				   denim_weight: 12,
				   sanforized: true,
				   stretch: true,
				   selvedge: true,
				   price: "185.00",
				   link: "http://www.contextclothing.com/item.php?id=665")

	Item.create!(name: "Petit Standard",
				   brand: "APC",
				   tag_size: 27,
				   waist: 28,
				   front_rise: 9,
				   thigh: 10,
				   knee: 7,
				   leg_opening: 6,
				   inseam: 33,
				   color: "Indigo",
				   fabric_origin: "China",
				   made_in: "China",
				   denim_weight: 12,
				   sanforized: true,
				   stretch: true,
				   selvedge: true,
				   price: "185.00",
				   link: "http://www.contextclothing.com/item.php?id=665")

	Item.create!(name: "Petit Standard",
				   brand: "APC",
				   tag_size: 28,
				   waist: 29,
				   front_rise: 9,
				   thigh: 10.5,
				   knee: 7.5,
				   leg_opening: 6.5,
				   inseam: 33,
				   color: "Indigo",
				   fabric_origin: "China",
				   made_in: "China",
				   denim_weight: 12,
				   sanforized: true,
				   stretch: true,
				   selvedge: true,
				   price: "185.00",
				   link: "http://www.contextclothing.com/item.php?id=665")

	Item.create!(name: "Petit Standard",
				   brand: "APC",
				   tag_size: 29,
				   waist: 30,
				   front_rise: 9.5,
				   thigh: 10.5,
				   knee: 7.5,
				   leg_opening: 6.5,
				   inseam: 33.5,
				   color: "Indigo",
				   fabric_origin: "China",
				   made_in: "China",
				   denim_weight: 12,
				   sanforized: true,
				   stretch: true,
				   selvedge: true,
				   price: "185.00",
				   link: "http://www.contextclothing.com/item.php?id=665")

	Item.create!(name: "Petit Standard",
				   brand: "APC",
				   tag_size: 30,
				   waist: 31,
				   front_rise: 9.5,
				   thigh: 10.5,
				   knee: 7.5,
				   leg_opening: 6.5,
				   inseam: 33.5,
				   color: "Indigo",
				   fabric_origin: "China",
				   made_in: "China",
				   denim_weight: 12,
				   sanforized: true,
				   stretch: true,
				   selvedge: true,
				   price: "185.00",
				   link: "http://www.contextclothing.com/item.php?id=665")

	Item.create!(name: "Petit Standard",
				   brand: "APC",
				   tag_size: 31,
				   waist: 32,
				   front_rise: 9.5,
				   thigh: 11,
				   knee: 8,
				   leg_opening: 7,
				   inseam: 33.5,
				   color: "Indigo",
				   fabric_origin: "China",
				   made_in: "China",
				   denim_weight: 12,
				   sanforized: true,
				   stretch: true,
				   selvedge: true,
				   price: "185.00",
				   link: "http://www.contextclothing.com/item.php?id=665")

	Item.create!(name: "Petit Standard",
				   brand: "APC",
				   tag_size: 32,
				   waist: 33,
				   front_rise: 10,
				   thigh: 11.5,
				   knee: 8,
				   leg_opening: 7,
				   inseam: 34,
				   color: "Indigo",
				   fabric_origin: "China",
				   made_in: "China",
				   denim_weight: 12,
				   sanforized: true,
				   stretch: true,
				   selvedge: true,
				   price: "185.00",
				   link: "http://www.contextclothing.com/item.php?id=665")

	Item.create!(name: "Petit Standard",
				   brand: "APC",
				   tag_size: 33,
				   waist: 34,
				   front_rise: 10,
				   thigh: 12,
				   knee: 8.5,
				   leg_opening: 7.5,
				   inseam: 34,
				   color: "Indigo",
				   fabric_origin: "China",
				   made_in: "China",
				   denim_weight: 12,
				   sanforized: true,
				   stretch: true,
				   selvedge: true,
				   price: "185.00",
				   link: "http://www.contextclothing.com/item.php?id=665")

#APC Rescue-------------------------------------------------
	Item.create!(name: "Rescue",
				   brand: "APC",
				   tag_size: 28,
				   waist: 29,
				   front_rise: 10,
				   thigh: 11,
				   knee: 8,
				   leg_opening: 8,
				   inseam: 33.5,
				   color: "Indigo",
				   fabric_origin: "China",
				   made_in: "China",
				   denim_weight: 12,
				   sanforized: true,
				   stretch: true,
				   selvedge: true,
				   price: "185.00",
				   link: "http://www.contextclothing.com/item.php?id=7")

	Item.create!(name: "Rescue",
				   brand: "APC",
				   tag_size: 29,
				   waist: 30,
				   front_rise: 10,
				   thigh: 11.5,
				   knee: 8,
				   leg_opening: 8,
				   inseam: 33.5,
				   color: "Indigo",
				   fabric_origin: "China",
				   made_in: "China",
				   denim_weight: 12,
				   sanforized: true,
				   stretch: true,
				   selvedge: true,
				   price: "185.00",
				   link: "http://www.contextclothing.com/item.php?id=7")

	Item.create!(name: "Rescue",
				   brand: "APC",
				   tag_size: 30,
				   waist: 31,
				   front_rise: 10,
				   thigh: 11.5,
				   knee: 8.5,
				   leg_opening: 8.5,
				   inseam: 34,
				   color: "Indigo",
				   fabric_origin: "China",
				   made_in: "China",
				   denim_weight: 12,
				   sanforized: true,
				   stretch: true,
				   selvedge: true,
				   price: "185.00",
				   link: "http://www.contextclothing.com/item.php?id=7")

	Item.create!(name: "Rescue",
				   brand: "APC",
				   tag_size: 31,
				   waist: 32,
				   front_rise: 10.5,
				   thigh: 12,
				   knee: 8.5,
				   leg_opening: 8.5,
				   inseam: 34,
				   color: "Indigo",
				   fabric_origin: "China",
				   made_in: "China",
				   denim_weight: 12,
				   sanforized: true,
				   stretch: true,
				   selvedge: true,
				   price: "185.00",
				   link: "http://www.contextclothing.com/item.php?id=7")

	Item.create!(name: "Rescue",
				   brand: "APC",
				   tag_size: 32,
				   waist: 33,
				   front_rise: 10.5,
				   thigh: 12,
				   knee: 9,
				   leg_opening: 9,
				   inseam: 34,
				   color: "Indigo",
				   fabric_origin: "China",
				   made_in: "China",
				   denim_weight: 12,
				   sanforized: true,
				   stretch: true,
				   selvedge: true,
				   price: "185.00",
				   link: "http://www.contextclothing.com/item.php?id=7")

	Item.create!(name: "Rescue",
				   brand: "APC",
				   tag_size: 33,
				   waist: 34,
				   front_rise: 10.5,
				   thigh: 12,
				   knee: 9,
				   leg_opening: 9,
				   inseam: 34,
				   color: "Indigo",
				   fabric_origin: "China",
				   made_in: "China",
				   denim_weight: 12,
				   sanforized: true,
				   stretch: true,
				   selvedge: true,
				   price: "185.00",
				   link: "http://www.contextclothing.com/item.php?id=7")

		Item.create!(name: "Rescue",
				   brand: "APC",
				   tag_size: 34,
				   waist: 35,
				   front_rise: 11,
				   thigh: 12.5,
				   knee: 9.5,
				   leg_opening: 9.5,
				   inseam: 34.5,
				   color: "Indigo",
				   fabric_origin: "China",
				   made_in: "China",
				   denim_weight: 12,
				   sanforized: true,
				   stretch: true,
				   selvedge: true,
				   price: "185.00",
				   link: "http://www.contextclothing.com/item.php?id=7")

	Item.create!(name: "Rescue",
				   brand: "APC",
				   tag_size: 35,
				   waist: 36,
				   front_rise: 11,
				   thigh: 13,
				   knee: 9.5,
				   leg_opening: 9.5,
				   inseam: 35,
				   color: "Indigo",
				   fabric_origin: "China",
				   made_in: "China",
				   denim_weight: 12,
				   sanforized: true,
				   stretch: true,
				   selvedge: true,
				   price: "185.00",
				   link: "http://www.contextclothing.com/item.php?id=7")
	
	Item.create!(name: "Rescue",
				   brand: "APC",
				   tag_size: 36,
				   waist: 37,
				   front_rise: 11,
				   thigh: 13,
				   knee: 10,
				   leg_opening: 10,
				   inseam: 35,
				   color: "Indigo",
				   fabric_origin: "China",
				   made_in: "China",
				   denim_weight: 12,
				   sanforized: true,
				   stretch: true,
				   selvedge: true,
				   price: "185.00",
				   link: "http://www.contextclothing.com/item.php?id=7")

#APC Petit New Standard-------------------------------------------
	Item.create!(name: "Petit New Standard",
				   brand: "APC",
				   tag_size: 25,
				   waist: 26,
				   front_rise: 9.25,
				   thigh: 9.5,
				   knee: 6.75,
				   leg_opening: 6.25,
				   inseam: 32.5,
				   color: "Indigo",
				   fabric_origin: "China",
				   made_in: "China",
				   denim_weight: 12,
				   sanforized: true,
				   stretch: true,
				   selvedge: true,
				   price: "185.00",
				   link: "http://www.contextclothing.com/item.php?id=3941")
	
	Item.create!(name: "Petit New Standard",
				   brand: "APC",
				   tag_size: 26,
				   waist: 27,
				   front_rise: 9.5,
				   thigh: 10,
				   knee: 7,
				   leg_opening: 6.5,
				   inseam: 32.5,
				   color: "Indigo",
				   fabric_origin: "China",
				   made_in: "China",
				   denim_weight: 12,
				   sanforized: true,
				   stretch: true,
				   selvedge: true,
				   price: "185.00",
				   link: "http://www.contextclothing.com/item.php?id=3941")

	Item.create!(name: "Petit New Standard",
				   brand: "APC",
				   tag_size: 27,
				   waist: 28,
				   front_rise: 9.5,
				   thigh: 10.25,
				   knee: 7,
				   leg_opening: 6.5,
				   inseam: 32.5,
				   color: "Indigo",
				   fabric_origin: "China",
				   made_in: "China",
				   denim_weight: 12,
				   sanforized: true,
				   stretch: true,
				   selvedge: true,
				   price: "185.00",
				   link: "http://www.contextclothing.com/item.php?id=3941")

	Item.create!(name: "Petit New Standard",
				   brand: "APC",
				   tag_size: 28,
				   waist: 29,
				   front_rise: 9.75,
				   thigh: 10.75,
				   knee: 7.5,
				   leg_opening: 6.5,
				   inseam: 32.5,
				   color: "Indigo",
				   fabric_origin: "China",
				   made_in: "China",
				   denim_weight: 12,
				   sanforized: true,
				   stretch: true,
				   selvedge: true,
				   price: "185.00",
				   link: "http://www.contextclothing.com/item.php?id=3941")

	Item.create!(name: "Petit New Standard",
				   brand: "APC",
				   tag_size: 29,
				   waist: 30,
				   front_rise: 9.75,
				   thigh: 11,
				   knee: 7.5,
				   leg_opening: 6.5,
				   inseam: 32.5,
				   color: "Indigo",
				   fabric_origin: "China",
				   made_in: "China",
				   denim_weight: 12,
				   sanforized: true,
				   stretch: true,
				   selvedge: true,
				   price: "185.00",
				   link: "http://www.contextclothing.com/item.php?id=3941")

	Item.create!(name: "Petit New Standard",
				   brand: "APC",
				   tag_size: 30,
				   waist: 31,
				   front_rise: 10,
				   thigh: 11,
				   knee: 7.75,
				   leg_opening: 6.75,
				   inseam: 33.5,
				   color: "Indigo",
				   fabric_origin: "China",
				   made_in: "China",
				   denim_weight: 12,
				   sanforized: true,
				   stretch: true,
				   selvedge: true,
				   price: "185.00",
				   link: "http://www.contextclothing.com/item.php?id=3941")

	Item.create!(name: "Petit New Standard",
				   brand: "APC",
				   tag_size: 31,
				   waist: 32,
				   front_rise: 10,
				   thigh: 11.25,
				   knee: 8,
				   leg_opening: 6.75,
				   inseam: 33.5,
				   color: "Indigo",
				   fabric_origin: "China",
				   made_in: "China",
				   denim_weight: 12,
				   sanforized: true,
				   stretch: true,
				   selvedge: true,
				   price: "185.00",
				   link: "http://www.contextclothing.com/item.php?id=3941")

	Item.create!(name: "Petit New Standard",
				   brand: "APC",
				   tag_size: 32,
				   waist: 33,
				   front_rise: 10,
				   thigh: 11.5,
				   knee: 8.25,
				   leg_opening: 7,
				   inseam: 33.5,
				   color: "Indigo",
				   fabric_origin: "China",
				   made_in: "China",
				   denim_weight: 12,
				   sanforized: true,
				   stretch: true,
				   selvedge: true,
				   price: "185.00",
				   link: "http://www.contextclothing.com/item.php?id=3941")

	Item.create!(name: "Petit New Standard",
				   brand: "APC",
				   tag_size: 33,
				   waist: 34,
				   front_rise: 10,
				   thigh: 11.75,
				   knee: 8.5,
				   leg_opening: 7.5,
				   inseam: 33.5,
				   color: "Indigo",
				   fabric_origin: "China",
				   made_in: "China",
				   denim_weight: 12,
				   sanforized: true,
				   stretch: true,
				   selvedge: true,
				   price: "185.00",
				   link: "http://www.contextclothing.com/item.php?id=3941")

	Item.create!(name: "Petit New Standard",
				   brand: "APC",
				   tag_size: 34,
				   waist: 35,
				   front_rise: 10.25,
				   thigh: 12.25,
				   knee: 8.75,
				   leg_opening: 7.5,
				   inseam: 33.5,
				   color: "Indigo",
				   fabric_origin: "China",
				   made_in: "China",
				   denim_weight: 12,
				   sanforized: true,
				   stretch: true,
				   selvedge: true,
				   price: "185.00",
				   link: "http://www.contextclothing.com/item.php?id=3941")

#APC New Cure----------------------------------------------
	Item.create!(name: "New Cure",
				   brand: "APC",
				   tag_size: 25,
				   waist: 26,
				   front_rise: 8.5,
				   thigh: 9.5,
				   knee: 6.5,
				   leg_opening: 6.5,
				   inseam: 33.5,
				   color: "Indigo",
				   fabric_origin: "China",
				   made_in: "China",
				   denim_weight: 12,
				   sanforized: true,
				   stretch: true,
				   selvedge: true,
				   price: "185.00",
				   link: "http://www.contextclothing.com/item.php?id=29")

	Item.create!(name: "New Cure",
				   brand: "APC",
				   tag_size: 26,
				   waist: 27,
				   front_rise: 9,
				   thigh: 9.5,
				   knee: 6.5,
				   leg_opening: 6.5,
				   inseam: 33.5,
				   color: "Indigo",
				   fabric_origin: "China",
				   made_in: "China",
				   denim_weight: 12,
				   sanforized: true,
				   stretch: true,
				   selvedge: true,
				   price: "185.00",
				   link: "http://www.contextclothing.com/item.php?id=29")

	Item.create!(name: "New Cure",
				   brand: "APC",
				   tag_size: 27,
				   waist: 28,
				   front_rise: 9,
				   thigh: 10,
				   knee: 6.5,
				   leg_opening: 6.5,
				   inseam: 33.5,
				   color: "Indigo",
				   fabric_origin: "China",
				   made_in: "China",
				   denim_weight: 12,
				   sanforized: true,
				   stretch: true,
				   selvedge: true,
				   price: "185.00",
				   link: "http://www.contextclothing.com/item.php?id=29")

	Item.create!(name: "New Cure",
				   brand: "APC",
				   tag_size: 28,
				   waist: 29,
				   front_rise: 9.5,
				   thigh: 10.5,
				   knee: 7,
				   leg_opening: 7,
				   inseam: 33.5,
				   color: "Indigo",
				   fabric_origin: "China",
				   made_in: "China",
				   denim_weight: 12,
				   sanforized: true,
				   stretch: true,
				   selvedge: true,
				   price: "185.00",
				   link: "http://www.contextclothing.com/item.php?id=29")

	Item.create!(name: "New Cure",
				   brand: "APC",
				   tag_size: 29,
				   waist: 30,
				   front_rise: 9.5,
				   thigh: 10.5,
				   knee: 7,
				   leg_opening: 7,
				   inseam: 33.5,
				   color: "Indigo",
				   fabric_origin: "China",
				   made_in: "China",
				   denim_weight: 12,
				   sanforized: true,
				   stretch: true,
				   selvedge: true,
				   price: "185.00",
				   link: "http://www.contextclothing.com/item.php?id=29")

	Item.create!(name: "New Cure",
				   brand: "APC",
				   tag_size: 30,
				   waist: 31,
				   front_rise: 9.5,
				   thigh: 10.5,
				   knee: 7.5,
				   leg_opening: 7.5,
				   inseam: 34,
				   color: "Indigo",
				   fabric_origin: "China",
				   made_in: "China",
				   denim_weight: 12,
				   sanforized: true,
				   stretch: true,
				   selvedge: true,
				   price: "185.00",
				   link: "http://www.contextclothing.com/item.php?id=29")

	Item.create!(name: "New Cure",
				   brand: "APC",
				   tag_size: 31,
				   waist: 32,
				   front_rise: 9.5,
				   thigh: 11,
				   knee: 7.5,
				   leg_opening: 7.5,
				   inseam: 35,
				   color: "Indigo",
				   fabric_origin: "China",
				   made_in: "China",
				   denim_weight: 12,
				   sanforized: true,
				   stretch: true,
				   selvedge: true,
				   price: "185.00",
				   link: "http://www.contextclothing.com/item.php?id=29")

	Item.create!(name: "New Cure",
				   brand: "APC",
				   tag_size: 32,
				   waist: 33,
				   front_rise: 10,
				   thigh: 11,
				   knee: 8,
				   leg_opening: 8,
				   inseam: 35.5,
				   color: "Indigo",
				   fabric_origin: "China",
				   made_in: "China",
				   denim_weight: 12,
				   sanforized: true,
				   stretch: true,
				   selvedge: true,
				   price: "185.00",
				   link: "http://www.contextclothing.com/item.php?id=29")

	Item.create!(name: "New Cure",
				   brand: "APC",
				   tag_size: 33,
				   waist: 34,
				   front_rise: 10,
				   thigh: 11.5,
				   knee: 8,
				   leg_opening: 8,
				   inseam: 36,
				   color: "Indigo",
				   fabric_origin: "China",
				   made_in: "China",
				   denim_weight: 12,
				   sanforized: true,
				   stretch: true,
				   selvedge: true,
				   price: "185.00",
				   link: "http://www.contextclothing.com/item.php?id=29")

#Unbranded 101---------------------------------------
	Item.create!(name: "101",
				   brand: "Unbranded",
				   tag_size: 29,
				   waist: 29.5,
				   front_rise: 9.1,
				   thigh: 10.5,
				   knee: 7.5,
				   leg_opening: 7,
				   inseam: 36.5,
				   color: "Indigo",
				   fabric_origin: "Japan",
				   made_in: "China",
				   denim_weight: 14.5,
				   sanforized: true,
				   stretch: false,
				   selvedge: true,
				   price: "78.00",
				   link: "http://www.rueandstate.com/collections/unbranded/products/unbranded-101-indigo-skinny-straight-raw-denim")

	Item.create!(name: "101",
				   brand: "Unbranded",
				   tag_size: 30,
				   waist: 30.5,
				   front_rise: 9.3,
				   thigh: 10.75,
				   knee: 7.75,
				   leg_opening: 7.1,
				   inseam: 36.5,
				   color: "Indigo",
				   fabric_origin: "Japan",
				   made_in: "China",
				   denim_weight: 14.5,
				   sanforized: true,
				   stretch: false,
				   selvedge: true,
				   price: "78.00",
				   link: "http://www.rueandstate.com/collections/unbranded/products/unbranded-101-indigo-skinny-straight-raw-denim")

	Item.create!(name: "101",
				   brand: "Unbranded",
				   tag_size: 31,
				   waist: 31.5,
				   front_rise: 9.4,
				   thigh: 11,
				   knee: 8,
				   leg_opening: 7.25,
				   inseam: 36.5,
				   color: "Indigo",
				   fabric_origin: "Japan",
				   made_in: "China",
				   denim_weight: 14.5,
				   sanforized: true,
				   stretch: false,
				   selvedge: true,
				   price: "78.00",
				   link: "http://www.rueandstate.com/collections/unbranded/products/unbranded-101-indigo-skinny-straight-raw-denim")

	Item.create!(name: "101",
				   brand: "Unbranded",
				   tag_size: 32,
				   waist: 32.5,
				   front_rise: 9.5,
				   thigh: 11,
				   knee: 8.25,
				   leg_opening: 7.25,
				   inseam: 36.5,
				   color: "Indigo",
				   fabric_origin: "Japan",
				   made_in: "China",
				   denim_weight: 14.5,
				   sanforized: true,
				   stretch: false,
				   selvedge: true,
				   price: "78.00",
				   link: "http://www.rueandstate.com/collections/unbranded/products/unbranded-101-indigo-skinny-straight-raw-denim")

	Item.create!(name: "101",
				   brand: "Unbranded",
				   tag_size: 33,
				   waist: 33.5,
				   front_rise: 9.75,
				   thigh: 11.3,
				   knee: 8.5,
				   leg_opening: 7.25,
				   inseam: 36.5,
				   color: "Indigo",
				   fabric_origin: "Japan",
				   made_in: "China",
				   denim_weight: 14.5,
				   sanforized: true,
				   stretch: false,
				   selvedge: true,
				   price: "78.00",
				   link: "http://www.rueandstate.com/collections/unbranded/products/unbranded-101-indigo-skinny-straight-raw-denim")

	Item.create!(name: "101",
				   brand: "Unbranded",
				   tag_size: 34,
				   waist: 34.5,
				   front_rise: 9.8,
				   thigh: 11.5,
				   knee: 8.5,
				   leg_opening: 7.5,
				   inseam: 36.5,
				   color: "Indigo",
				   fabric_origin: "Japan",
				   made_in: "China",
				   denim_weight: 14.5,
				   sanforized: true,
				   stretch: false,
				   selvedge: true,
				   price: "78.00",
				   link: "http://www.rueandstate.com/collections/unbranded/products/unbranded-101-indigo-skinny-straight-raw-denim")

	Item.create!(name: "101",
				   brand: "Unbranded",
				   tag_size: 36,
				   waist: 36,
				   front_rise: 10,
				   thigh: 12,
				   knee: 9,
				   leg_opening: 8,
				   inseam: 36.5,
				   color: "Indigo",
				   fabric_origin: "Japan",
				   made_in: "China",
				   denim_weight: 14.5,
				   sanforized: true,
				   stretch: false,
				   selvedge: true,
				   price: "78.00",
				   link: "http://www.rueandstate.com/collections/unbranded/products/unbranded-101-indigo-skinny-straight-raw-denim")

#Unbranded 201------------------------------------------
	Item.create!(name: "201",
				   brand: "Unbranded",
				   tag_size: 28,
				   waist: 28.25,
				   front_rise: 9.5,
				   thigh: 10.5,
				   knee: 7.5,
				   leg_opening: 7,
				   inseam: 34.5,
				   color: "Indigo",
				   fabric_origin: "Japan",
				   made_in: "China",
				   denim_weight: 14.5,
				   sanforized: true,
				   stretch: false,
				   selvedge: true,
				   price: "78.00",
				   link: "http://www.rueandstate.com/collections/unbranded/products/unbranded-201-indigo-tapered")

	Item.create!(name: "201",
				   brand: "Unbranded",
				   tag_size: 29,
				   waist: 29.75,
				   front_rise: 9.9,
				   thigh: 10.8,
				   knee: 7.75,
				   leg_opening: 7,
				   inseam: 34.5,
				   color: "Indigo",
				   fabric_origin: "Japan",
				   made_in: "China",
				   denim_weight: 14.5,
				   sanforized: true,
				   stretch: false,
				   selvedge: true,
				   price: "78.00",
				   link: "http://www.rueandstate.com/collections/unbranded/products/unbranded-201-indigo-tapered")

	Item.create!(name: "201",
				   brand: "Unbranded",
				   tag_size: 30,
				   waist: 30.75,
				   front_rise: 10,
				   thigh: 11,
				   knee: 7.9,
				   leg_opening: 7.25,
				   inseam: 34.5,
				   color: "Indigo",
				   fabric_origin: "Japan",
				   made_in: "China",
				   denim_weight: 14.5,
				   sanforized: true,
				   stretch: false,
				   selvedge: true,
				   price: "78.00",
				   link: "http://www.rueandstate.com/collections/unbranded/products/unbranded-201-indigo-tapered")

	Item.create!(name: "201",
				   brand: "Unbranded",
				   tag_size: 31,
				   waist: 31.75,
				   front_rise: 10.2,
				   thigh: 11.5,
				   knee: 8.25,
				   leg_opening: 7.4,
				   inseam: 34.5,
				   color: "Indigo",
				   fabric_origin: "Japan",
				   made_in: "China",
				   denim_weight: 14.5,
				   sanforized: true,
				   stretch: false,
				   selvedge: true,
				   price: "78.00",
				   link: "http://www.rueandstate.com/collections/unbranded/products/unbranded-201-indigo-tapered")

	Item.create!(name: "201",
				   brand: "Unbranded",
				   tag_size: 32,
				   waist: 32.75,
				   front_rise: 10.25,
				   thigh: 11.8,
				   knee: 8.4,
				   leg_opening: 7.6,
				   inseam: 34.5,
				   color: "Indigo",
				   fabric_origin: "Japan",
				   made_in: "China",
				   denim_weight: 14.5,
				   sanforized: true,
				   stretch: false,
				   selvedge: true,
				   price: "78.00",
				   link: "http://www.rueandstate.com/collections/unbranded/products/unbranded-201-indigo-tapered")

	Item.create!(name: "201",
				   brand: "Unbranded",
				   tag_size: 33,
				   waist: 33.75,
				   front_rise: 10.4,
				   thigh: 12,
				   knee: 8.5,
				   leg_opening: 7.7,
				   inseam: 34.5,
				   color: "Indigo",
				   fabric_origin: "Japan",
				   made_in: "China",
				   denim_weight: 14.5,
				   sanforized: true,
				   stretch: false,
				   selvedge: true,
				   price: "78.00",
				   link: "http://www.rueandstate.com/collections/unbranded/products/unbranded-201-indigo-tapered")

	Item.create!(name: "201",
				   brand: "Unbranded",
				   tag_size: 34,
				   waist: 34.75,
				   front_rise: 10.5,
				   thigh: 12.5,
				   knee: 8.75,
				   leg_opening: 7.8,
				   inseam: 34.5,
				   color: "Indigo",
				   fabric_origin: "Japan",
				   made_in: "China",
				   denim_weight: 14.5,
				   sanforized: true,
				   stretch: false,
				   selvedge: true,
				   price: "78.00",
				   link: "http://www.rueandstate.com/collections/unbranded/products/unbranded-201-indigo-tapered")

	Item.create!(name: "201",
				   brand: "Unbranded",
				   tag_size: 36,
				   waist: 35.75,
				   front_rise: 10.5,
				   thigh: 12.75,
				   knee: 9.25,
				   leg_opening: 7.9,
				   inseam: 34.5,
				   color: "Indigo",
				   fabric_origin: "Japan",
				   made_in: "China",
				   denim_weight: 14.5,
				   sanforized: true,
				   stretch: false,
				   selvedge: true,
				   price: "78.00",
				   link: "http://www.rueandstate.com/collections/unbranded/products/unbranded-201-indigo-tapered")

#Unbranded 301

	Item.create!(name: "301",
				   brand: "Unbranded",
				   tag_size: 30,
				   waist: 31,
				   front_rise: 10,
				   thigh: 11.5,
				   knee: 8.3,
				   leg_opening: 8.2,
				   inseam: 34,
				   color: "Indigo",
				   fabric_origin: "Japan",
				   made_in: "China",
				   denim_weight: 14.5,
				   sanforized: true,
				   stretch: false,
				   selvedge: true,
				   price: "82.00",
				   link: "http://www.blueowl.us/product/unbranded-straight-leg-145oz-selvedge-in-indigo-model-ub301/")

	Item.create!(name: "301",
				   brand: "Unbranded",
				   tag_size: 31,
				   waist: 32,
				   front_rise: 10,
				   thigh: 11.5,
				   knee: 8.4,
				   leg_opening: 8.4,
				   inseam: 34,
				   color: "Indigo",
				   fabric_origin: "Japan",
				   made_in: "China",
				   denim_weight: 14.5,
				   sanforized: true,
				   stretch: false,
				   selvedge: true,
				   price: "82.00",
				   link: "http://www.blueowl.us/product/unbranded-straight-leg-145oz-selvedge-in-indigo-model-ub301/")

	Item.create!(name: "301",
				   brand: "Unbranded",
				   tag_size: 32,
				   waist: 33,
				   front_rise: 10.25,
				   thigh: 11.75,
				   knee: 8.65,
				   leg_opening: 8.6,
				   inseam: 34,
				   color: "Indigo",
				   fabric_origin: "Japan",
				   made_in: "China",
				   denim_weight: 14.5,
				   sanforized: true,
				   stretch: false,
				   selvedge: true,
				   price: "82.00",
				   link: "http://www.blueowl.us/product/unbranded-straight-leg-145oz-selvedge-in-indigo-model-ub301/")

	Item.create!(name: "301",
				   brand: "Unbranded",
				   tag_size: 34,
				   waist: 35,
				   front_rise: 10.25,
				   thigh: 11.75,
				   knee: 8.9,
				   leg_opening: 8.8,
				   inseam: 34,
				   color: "Indigo",
				   fabric_origin: "Japan",
				   made_in: "China",
				   denim_weight: 14.5,
				   sanforized: true,
				   stretch: false,
				   selvedge: true,
				   price: "82.00",
				   link: "http://www.blueowl.us/product/unbranded-straight-leg-145oz-selvedge-in-indigo-model-ub301/")

#Unbranded 121-------------------------------------------------
	Item.create!(name: "121",
				   brand: "Unbranded",
					tag_size: 28,
					waist: 29.5,
					front_rise: 9,
					thigh: 10,
					knee: 7.3,
					leg_opening: 6.65,
					inseam: 36.5,
				   color: "Indigo",
				   fabric_origin: "Japan",
				   made_in: "China",
				   denim_weight: 21,
				   sanforized: true,
				   stretch: false,
				   selvedge: true,
				   price: "110.00",
				   link: "http://www.blueowl.us/product/unbranded-skinny-leg-21oz-heavyweight-selvedge-in-indigo-model-ub121/")

	Item.create!(name: "121",
				   brand: "Unbranded",
					tag_size: 29,
					waist: 30.5,
					front_rise: 9,
					thigh: 10.25,
					knee: 7.7,
					leg_opening: 6.75,
					inseam: 36.5,
				   color: "Indigo",
				   fabric_origin: "Japan",
				   made_in: "China",
				   denim_weight: 21,
				   sanforized: true,
				   stretch: false,
				   selvedge: true,
				   price: "110.00",
				   link: "http://www.blueowl.us/product/unbranded-skinny-leg-21oz-heavyweight-selvedge-in-indigo-model-ub121/")

	Item.create!(name: "121",
				   brand: "Unbranded",
					tag_size: 30,
					waist: 31.5,
					front_rise: 9.25,
					thigh: 10.5,
					knee: 7.85,
					leg_opening: 7,
					inseam: 36.5,
				   color: "Indigo",
				   fabric_origin: "Japan",
				   made_in: "China",
				   denim_weight: 21,
				   sanforized: true,
				   stretch: false,
				   selvedge: true,
				   price: "110.00",
				   link: "http://www.blueowl.us/product/unbranded-skinny-leg-21oz-heavyweight-selvedge-in-indigo-model-ub121/")

	Item.create!(name: "121",
				   brand: "Unbranded",
					tag_size: 31,
					waist: 32.5,
					front_rise: 9.3,
					thigh: 10.75,
					knee: 8,
					leg_opening: 7,
					inseam: 36.5,
				   color: "Indigo",
				   fabric_origin: "Japan",
				   made_in: "China",
				   denim_weight: 21,
				   sanforized: true,
				   stretch: false,
				   selvedge: true,
				   price: "110.00",
				   link: "http://www.blueowl.us/product/unbranded-skinny-leg-21oz-heavyweight-selvedge-in-indigo-model-ub121/")

	Item.create!(name: "121",
				   brand: "Unbranded",
					tag_size: 32,
					waist: 33.5,
					front_rise: 9.4,
					thigh: 11,
					knee: 8.25,
					leg_opening: 7.25,
					inseam: 36.5,
				   color: "Indigo",
				   fabric_origin: "Japan",
				   made_in: "China",
				   denim_weight: 21,
				   sanforized: true,
				   stretch: false,
				   selvedge: true,
				   price: "110.00",
				   link: "http://www.blueowl.us/product/unbranded-skinny-leg-21oz-heavyweight-selvedge-in-indigo-model-ub121/")

	Item.create!(name: "121",
				   brand: "Unbranded",
					tag_size: 33,
					waist: 34.5,
					front_rise: 9.65,
					thigh: 11.25,
					knee: 8.45,
					leg_opening: 7.35,
					inseam: 36.5,
				   color: "Indigo",
				   fabric_origin: "Japan",
				   made_in: "China",
				   denim_weight: 21,
				   sanforized: true,
				   stretch: false,
				   selvedge: true,
				   price: "110.00",
				   link: "http://www.blueowl.us/product/unbranded-skinny-leg-21oz-heavyweight-selvedge-in-indigo-model-ub121/")

	Item.create!(name: "121",
				   brand: "Unbranded",
					tag_size: 34,
					waist: 35.5,
					front_rise: 9.75,
					thigh: 11.5,
					knee: 8.6,
					leg_opening: 7.5,
					inseam: 36.5,
				   color: "Indigo",
				   fabric_origin: "Japan",
				   made_in: "China",
				   denim_weight: 21,
				   sanforized: true,
				   stretch: false,
				   selvedge: true,
				   price: "110.00",
				   link: "http://www.blueowl.us/product/unbranded-skinny-leg-21oz-heavyweight-selvedge-in-indigo-model-ub121/")

	Item.create!(name: "121",
				   brand: "Unbranded",
					tag_size: 36,
					waist: 37.5,
					front_rise: 10,
					thigh: 12,
					knee: 9,
					leg_opening: 7.75,
					inseam: 36.5,
				   color: "Indigo",
				   fabric_origin: "Japan",
				   made_in: "China",
				   denim_weight: 21,
				   sanforized: true,
				   stretch: false,
				   selvedge: true,
				   price: "110.00",
				   link: "http://www.blueowl.us/product/unbranded-skinny-leg-21oz-heavyweight-selvedge-in-indigo-model-ub121/")

	Item.create!(name: "121",
				   brand: "Unbranded",
					tag_size: 38,
					waist: 39.5,
					front_rise: 10.25,
					thigh: 12.5,
					knee: 9.25,
					leg_opening: 8,
					inseam: 36.5,
				   color: "Indigo",
				   fabric_origin: "Japan",
				   made_in: "China",
				   denim_weight: 21,
				   sanforized: true,
				   stretch: false,
				   selvedge: true,
				   price: "110.00",
				   link: "http://www.blueowl.us/product/unbranded-skinny-leg-21oz-heavyweight-selvedge-in-indigo-model-ub121/")

#Unbranded 221
		Item.create!(name: "221",
				   brand: "Unbranded",
					tag_size: 28,
					waist: 29.5,
					front_rise: 9.4,
					thigh: 10.75,
					knee: 7.25,
					leg_opening: 6.75,
					inseam: 34,
				   color: "Indigo",
				   fabric_origin: "Japan",
				   made_in: "China",
				   denim_weight: 21,
				   sanforized: true,
				   stretch: false,
				   selvedge: true,
				   price: "110.00",
				   link: "http://www.blueowl.us/product/unbranded-tapered-leg-21oz-heavyweight-selvedge-in-indigo-model-ub221/")

		Item.create!(name: "221",
				   brand: "Unbranded",
					tag_size: 29,
					waist: 30.5,
					front_rise: 9.65,
					thigh: 10.75,
					knee: 7.5,
					leg_opening: 7,
					inseam: 34,
				   color: "Indigo",
				   fabric_origin: "Japan",
				   made_in: "China",
				   denim_weight: 21,
				   sanforized: true,
				   stretch: false,
				   selvedge: true,
				   price: "110.00",
				   link: "http://www.blueowl.us/product/unbranded-tapered-leg-21oz-heavyweight-selvedge-in-indigo-model-ub221/")

		Item.create!(name: "221",
				   brand: "Unbranded",
					tag_size: 30,
					waist: 32,
					front_rise: 9.7,
					thigh: 11.25,
					knee: 7.65,
					leg_opening: 7.25,
					inseam: 34,
				   color: "Indigo",
				   fabric_origin: "Japan",
				   made_in: "China",
				   denim_weight: 21,
				   sanforized: true,
				   stretch: false,
				   selvedge: true,
				   price: "110.00",
				   link: "http://www.blueowl.us/product/unbranded-tapered-leg-21oz-heavyweight-selvedge-in-indigo-model-ub221/")

		Item.create!(name: "221",
				   brand: "Unbranded",
					tag_size: 31,
					waist: 32.5,
					front_rise: 10.85,
					thigh: 11.5,
					knee: 7.9,
					leg_opening: 7.5,
					inseam: 34,
				   color: "Indigo",
				   fabric_origin: "Japan",
				   made_in: "China",
				   denim_weight: 21,
				   sanforized: true,
				   stretch: false,
				   selvedge: true,
				   price: "110.00",
				   link: "http://www.blueowl.us/product/unbranded-tapered-leg-21oz-heavyweight-selvedge-in-indigo-model-ub221/")

		Item.create!(name: "221",
				   brand: "Unbranded",
					tag_size: 32,
					waist: 33.5,
					front_rise: 10,
					thigh: 11.65,
					knee: 8.15,
					leg_opening: 7.65,
					inseam: 34,
				   color: "Indigo",
				   fabric_origin: "Japan",
				   made_in: "China",
				   denim_weight: 21,
				   sanforized: true,
				   stretch: false,
				   selvedge: true,
				   price: "110.00",
				   link: "http://www.blueowl.us/product/unbranded-tapered-leg-21oz-heavyweight-selvedge-in-indigo-model-ub221/")

		Item.create!(name: "221",
				   brand: "Unbranded",
					tag_size: 33,
					waist: 34,
					front_rise: 10.15,
					thigh: 12,
					knee: 8.45,
					leg_opening: 7.85,
					inseam: 34,
				   color: "Indigo",
				   fabric_origin: "Japan",
				   made_in: "China",
				   denim_weight: 21,
				   sanforized: true,
				   stretch: false,
				   selvedge: true,
				   price: "110.00",
				   link: "http://www.blueowl.us/product/unbranded-tapered-leg-21oz-heavyweight-selvedge-in-indigo-model-ub221/")

		Item.create!(name: "221",
				   brand: "Unbranded",
					tag_size: 34,
					waist: 35.5,
					front_rise: 10.35,
					thigh: 12.25,
					knee: 8.55,
					leg_opening: 8,
					inseam: 34,
				   color: "Indigo",
				   fabric_origin: "Japan",
				   made_in: "China",
				   denim_weight: 21,
				   sanforized: true,
				   stretch: false,
				   selvedge: true,
				   price: "110.00",
				   link: "http://www.blueowl.us/product/unbranded-tapered-leg-21oz-heavyweight-selvedge-in-indigo-model-ub221/")

		Item.create!(name: "221",
				   brand: "Unbranded",
					tag_size: 36,
					waist: 37.25,
					front_rise: 10.35,
					thigh: 12.75,
					knee: 9,
					leg_opening: 8.3,
					inseam: 34.5,
				   color: "Indigo",
				   fabric_origin: "Japan",
				   made_in: "China",
				   denim_weight: 21,
				   sanforized: true,
				   stretch: false,
				   selvedge: true,
				   price: "110.00",
				   link: "http://www.blueowl.us/product/unbranded-tapered-leg-21oz-heavyweight-selvedge-in-indigo-model-ub221/")

		Item.create!(name: "221",
				   brand: "Unbranded",
					tag_size: 38,
					waist: 39.5,
					front_rise: 10.65,
					thigh: 13.25,
					knee: 9.45,
					leg_opening: 8.75,
					inseam: 34.5,
				   color: "Indigo",
				   fabric_origin: "Japan",
				   made_in: "China",
				   denim_weight: 21,
				   sanforized: true,
				   stretch: false,
				   selvedge: true,
				   price: "110.00",
				   link: "http://www.blueowl.us/product/unbranded-tapered-leg-21oz-heavyweight-selvedge-in-indigo-model-ub221/")

#Unbranded 321------------------------------------------------

	Item.create!(name: "321",
				   brand: "Unbranded",
					tag_size: 28,
					waist: 29,
					front_rise: 10,
					thigh: 11,
					knee: 8,
					leg_opening: 8,
					inseam: 34.5,
				   color: "Indigo",
				   fabric_origin: "Japan",
				   made_in: "China",
				   denim_weight: 21,
				   sanforized: true,
				   stretch: false,
				   selvedge: true,
				   price: "110.00",
				   link: "http://www.blueowl.us/product/unbranded-straight-leg-21oz-heavyweight-selvedge-in-indigo-model-ub321/")

	Item.create!(name: "321",
				   brand: "Unbranded",
					tag_size: 29,
					waist: 30,
					front_rise: 10.25,
					thigh: 11,
					knee: 8.2,
					leg_opening: 8.2,
					inseam: 34.5,
				   color: "Indigo",
				   fabric_origin: "Japan",
				   made_in: "China",
				   denim_weight: 21,
				   sanforized: true,
				   stretch: false,
				   selvedge: true,
				   price: "110.00",
				   link: "http://www.blueowl.us/product/unbranded-straight-leg-21oz-heavyweight-selvedge-in-indigo-model-ub321/")

	Item.create!(name: "321",
				   brand: "Unbranded",
					tag_size: 30,
					waist: 31,
					front_rise: 10.25,
					thigh: 11.25,
					knee: 8.4,
					leg_opening: 8.4,
					inseam: 34.5,
				   color: "Indigo",
				   fabric_origin: "Japan",
				   made_in: "China",
				   denim_weight: 21,
				   sanforized: true,
				   stretch: false,
				   selvedge: true,
				   price: "110.00",
				   link: "http://www.blueowl.us/product/unbranded-straight-leg-21oz-heavyweight-selvedge-in-indigo-model-ub321/")

	Item.create!(name: "321",
				   brand: "Unbranded",
					tag_size: 31,
					waist: 32,
					front_rise: 10.5,
					thigh: 11.5,
					knee: 8.5,
					leg_opening: 8.5,
					inseam: 34.5,
				   color: "Indigo",
				   fabric_origin: "Japan",
				   made_in: "China",
				   denim_weight: 21,
				   sanforized: true,
				   stretch: false,
				   selvedge: true,
				   price: "110.00",
				   link: "http://www.blueowl.us/product/unbranded-straight-leg-21oz-heavyweight-selvedge-in-indigo-model-ub321/")

	Item.create!(name: "321",
				   brand: "Unbranded",
					tag_size: 32,
					waist: 33,
					front_rise: 10.5,
					thigh: 11.75,
					knee: 8.6,
					leg_opening: 8.6,
					inseam: 34.5,
				   color: "Indigo",
				   fabric_origin: "Japan",
				   made_in: "China",
				   denim_weight: 21,
				   sanforized: true,
				   stretch: false,
				   selvedge: true,
				   price: "110.00",
				   link: "http://www.blueowl.us/product/unbranded-straight-leg-21oz-heavyweight-selvedge-in-indigo-model-ub321/")

	Item.create!(name: "321",
				   brand: "Unbranded",
					tag_size: 33,
					waist: 34,
					front_rise: 10.5,
					thigh: 12,
					knee: 8.8,
					leg_opening: 8.8,
					inseam: 34.5,
				   color: "Indigo",
				   fabric_origin: "Japan",
				   made_in: "China",
				   denim_weight: 21,
				   sanforized: true,
				   stretch: false,
				   selvedge: true,
				   price: "110.00",
				   link: "http://www.blueowl.us/product/unbranded-straight-leg-21oz-heavyweight-selvedge-in-indigo-model-ub321/")

	Item.create!(name: "321",
				   brand: "Unbranded",
					tag_size: 34,
					waist: 35,
					front_rise: 10.5,
					thigh: 12.25,
					knee: 9,
					leg_opening: 9,
					inseam: 34.5,
				   color: "Indigo",
				   fabric_origin: "Japan",
				   made_in: "China",
				   denim_weight: 21,
				   sanforized: true,
				   stretch: false,
				   selvedge: true,
				   price: "110.00",
				   link: "http://www.blueowl.us/product/unbranded-straight-leg-21oz-heavyweight-selvedge-in-indigo-model-ub321/")

	Item.create!(name: "321",
				   brand: "Unbranded",
					tag_size: 36,
					waist: 37,
					front_rise: 10.75,
					thigh: 12.75,
					knee: 9.5,
					leg_opening: 9.5,
					inseam: 34.5,
				   color: "Indigo",
				   fabric_origin: "Japan",
				   made_in: "China",
				   denim_weight: 21,
				   sanforized: true,
				   stretch: false,
				   selvedge: true,
				   price: "110.00",
				   link: "http://www.blueowl.us/product/unbranded-straight-leg-21oz-heavyweight-selvedge-in-indigo-model-ub321/")

	Item.create!(name: "321",
				   brand: "Unbranded",
					tag_size: 38,
					waist: 39,
					front_rise: 11.25,
					thigh: 13.25,
					knee: 9.75,
					leg_opening: 9.75,
					inseam: 34.5,
				   color: "Indigo",
				   fabric_origin: "Japan",
				   made_in: "China",
				   denim_weight: 21,
				   sanforized: true,
				   stretch: false,
				   selvedge: true,
				   price: "110.00",
				   link: "http://www.blueowl.us/product/unbranded-straight-leg-21oz-heavyweight-selvedge-in-indigo-model-ub321/")

#Baldwin Henley---------------------------------------------
	Item.create!(name: "The Henley",
				   brand: "Baldwin",
					tag_size: 28,
					waist: 30.5,
					front_rise: 9,
					thigh: 10.75,
					knee: 7.4,
					leg_opening: 6.8,
					inseam: 35,
				   color: "Indigo",
				   fabric_origin: "Kaihara Mills",
				   made_in: "USA",
				   denim_weight: 12.5,
				   sanforized: true,
				   stretch: false,
				   selvedge: true,
				   price: "220.00",
				   link: "http://www.blueowl.us/product/baldwin-denim-the-henley-125oz-kaihara-selvedge-denim-in-indigo/")

Item.create!(name: "The Henley",
				   brand: "Baldwin",
					tag_size: 29,
					waist: 31.5,
					front_rise: 9.25,
					thigh: 11,
					knee: 7.6,
					leg_opening: 7,
					inseam: 35,
				   color: "Indigo",
				   fabric_origin: "Kaihara Mills",
				   made_in: "USA",
				   denim_weight: 12.5,
				   sanforized: true,
				   stretch: false,
				   selvedge: true,
				   price: "220.00",
				   link: "http://www.blueowl.us/product/baldwin-denim-the-henley-125oz-kaihara-selvedge-denim-in-indigo/")

Item.create!(name: "The Henley",
				   brand: "Baldwin",
					tag_size: 30,
					waist: 33,
					front_rise: 9.75,
					thigh: 11.25,
					knee: 7.8,
					leg_opening: 7.2,
					inseam: 36,	
				   color: "Indigo",
				   fabric_origin: "Kaihara Mills",
				   made_in: "USA",
				   denim_weight: 12.5,
				   sanforized: true,
				   stretch: false,
				   selvedge: true,
				   price: "220.00",
				   link: "http://www.blueowl.us/product/baldwin-denim-the-henley-125oz-kaihara-selvedge-denim-in-indigo/")

Item.create!(name: "The Henley",
				   brand: "Baldwin",
					tag_size: 31,
					waist: 34,
					front_rise: 10,
					thigh: 11.5,
					knee: 7.9,
					leg_opening: 7.4,
					inseam: 36,
				   color: "Indigo",
				   fabric_origin: "Kaihara Mills",
				   made_in: "USA",
				   denim_weight: 12.5,
				   sanforized: true,
				   stretch: false,
				   selvedge: true,
				   price: "220.00",
				   link: "http://www.blueowl.us/product/baldwin-denim-the-henley-125oz-kaihara-selvedge-denim-in-indigo/")

Item.create!(name: "The Henley",
				   brand: "Baldwin",
					tag_size: 32,
					waist: 35,
					front_rise: 10.25,
					thigh: 11.75,
					knee: 8.1,
					leg_opening: 7.6,
					inseam: 36,
				   color: "Indigo",
				   fabric_origin: "Kaihara Mills",
				   made_in: "USA",
				   denim_weight: 12.5,
				   sanforized: true,
				   stretch: false,
				   selvedge: true,
				   price: "220.00",
				   link: "http://www.blueowl.us/product/baldwin-denim-the-henley-125oz-kaihara-selvedge-denim-in-indigo/")

Item.create!(name: "The Henley",
				   brand: "Baldwin",
					tag_size: 33,
					waist: 36,
					front_rise: 10.25,
					thigh: 12.25,
					knee: 8.3,
					leg_opening: 7.8,
					inseam: 36,
				   color: "Indigo",
				   fabric_origin: "Kaihara Mills",
				   made_in: "USA",
				   denim_weight: 12.5,
				   sanforized: true,
				   stretch: false,
				   selvedge: true,
				   price: "220.00",
				   link: "http://www.blueowl.us/product/baldwin-denim-the-henley-125oz-kaihara-selvedge-denim-in-indigo/")

Item.create!(name: "The Henley",
				   brand: "Baldwin",
					tag_size: 34,
					waist: 37,
					front_rise: 10.5,
					thigh: 12.25,
					knee: 8.5,
					leg_opening: 8.1,
					inseam: 36,
				   color: "Indigo",
				   fabric_origin: "Kaihara Mills",
				   made_in: "USA",
				   denim_weight: 12.5,
				   sanforized: true,
				   stretch: false,
				   selvedge: true,
				   price: "220.00",
				   link: "http://www.blueowl.us/product/baldwin-denim-the-henley-125oz-kaihara-selvedge-denim-in-indigo/")

Item.create!(name: "The Henley",
				   brand: "Baldwin",
					tag_size: 36,
					waist: 38.5,
					front_rise: 11,
					thigh: 13,
					knee: 8.8,
					leg_opening: 8.35,
					inseam: 36,
				   color: "Indigo",
				   fabric_origin: "Kaihara Mills",
				   made_in: "USA",
				   denim_weight: 12.5,
				   sanforized: true,
				   stretch: false,
				   selvedge: true,
				   price: "220.00",
				   link: "http://www.blueowl.us/product/baldwin-denim-the-henley-125oz-kaihara-selvedge-denim-in-indigo/")

#Baldwin Reed------------------------------------------------

	Item.create!(name: "The Reed",
				   brand: "Baldwin",
					tag_size: 28,
					waist: 30.5,
					front_rise: 8.5,
					thigh: 11,
					knee: 7.65,
					leg_opening: 7.1,
					inseam: 36,
				   color: "Indigo",
				   fabric_origin: "Kurabo Mills",
				   made_in: "USA",
				   denim_weight: 14,
				   sanforized: true,
				   stretch: false,
				   selvedge: true,
				   price: "220.00",
				   link: "http://www.blueowl.us/product/baldwin-denim-the-reed-14oz-kurabo-selvedge-denim-in-indigo/")

	Item.create!(name: "The Reed",
				   brand: "Baldwin",
					tag_size: 29,
					waist: 31.5,
					front_rise: 9,
					thigh: 11.25,
					knee: 7.9,
					leg_opening: 7.4,
					inseam: 36,
				   color: "Indigo",
				   fabric_origin: "Kurabo Mills",
				   made_in: "USA",
				   denim_weight: 14,
				   sanforized: true,
				   stretch: false,
				   selvedge: true,
				   price: "220.00",
				   link: "http://www.blueowl.us/product/baldwin-denim-the-reed-14oz-kurabo-selvedge-denim-in-indigo/")

	Item.create!(name: "The Reed",
				   brand: "Baldwin",
					tag_size: 30,
					waist: 33,
					front_rise: 9.25,
					thigh: 11.5,
					knee: 8.25,
					leg_opening: 7.7,
					inseam: 36,
				   color: "Indigo",
				   fabric_origin: "Kurabo Mills",
				   made_in: "USA",
				   denim_weight: 14,
				   sanforized: true,
				   stretch: false,
				   selvedge: true,
				   price: "220.00",
				   link: "http://www.blueowl.us/product/baldwin-denim-the-reed-14oz-kurabo-selvedge-denim-in-indigo/")

	Item.create!(name: "The Reed",
				   brand: "Baldwin",
					tag_size: 31,
					waist: 34.5,
					front_rise: 9.75,
					thigh: 11.75,
					knee: 8.5,
					leg_opening: 8,
					inseam: 36.5,
				   color: "Indigo",
				   fabric_origin: "Kurabo Mills",
				   made_in: "USA",
				   denim_weight: 14,
				   sanforized: true,
				   stretch: false,
				   selvedge: true,
				   price: "220.00",
				   link: "http://www.blueowl.us/product/baldwin-denim-the-reed-14oz-kurabo-selvedge-denim-in-indigo/")

	Item.create!(name: "The Reed",
				   brand: "Baldwin",
					tag_size: 32,
					waist: 35.5,
					front_rise: 10,
					thigh: 12,
					knee: 8.9,
					leg_opening: 8.35,
					inseam: 36.5,
				   color: "Indigo",
				   fabric_origin: "Kurabo Mills",
				   made_in: "USA",
				   denim_weight: 14,
				   sanforized: true,
				   stretch: false,
				   selvedge: true,
				   price: "220.00",
				   link: "http://www.blueowl.us/product/baldwin-denim-the-reed-14oz-kurabo-selvedge-denim-in-indigo/")

	Item.create!(name: "The Reed",
				   brand: "Baldwin",
					tag_size: 33,
					waist: 36.5,
					front_rise: 10.25,
					thigh: 12.25,
					knee: 9.15,
					leg_opening: 9,
					inseam: 36.5,
				   color: "Indigo",
				   fabric_origin: "Kurabo Mills",
				   made_in: "USA",
				   denim_weight: 14,
				   sanforized: true,
				   stretch: false,
				   selvedge: true,
				   price: "220.00",
				   link: "http://www.blueowl.us/product/baldwin-denim-the-reed-14oz-kurabo-selvedge-denim-in-indigo/")

	Item.create!(name: "The Reed",
				   brand: "Baldwin",
					tag_size: 34,
					waist: 37.5,
					front_rise: 10.5,
					thigh: 12.5,
					knee: 9.4,
					leg_opening: 9,
					inseam: 36.5,
				   color: "Indigo",
				   fabric_origin: "Kurabo Mills",
				   made_in: "USA",
				   denim_weight: 14,
				   sanforized: true,
				   stretch: false,
				   selvedge: true,
				   price: "220.00",
				   link: "http://www.blueowl.us/product/baldwin-denim-the-reed-14oz-kurabo-selvedge-denim-in-indigo/")

	Item.create!(name: "The Reed",
				   brand: "Baldwin",
					tag_size: 36,
					waist: 38.5,
					front_rise: 11.25,
					thigh: 13,
					knee: 9.7,
					leg_opening: 9.3,
					inseam: 36.5,
				   color: "Indigo",
				   fabric_origin: "Kurabo Mills",
				   made_in: "USA",
				   denim_weight: 14,
				   sanforized: true,
				   stretch: false,
				   selvedge: true,
				   price: "220.00",
				   link: "http://www.blueowl.us/product/baldwin-denim-the-reed-14oz-kurabo-selvedge-denim-in-indigo/")
#Baldwin Samuel--------------------------------------------------

	Item.create!(name: "The Samuel",
				   brand: "Baldwin",
					tag_size: 28,
					waist: 29.5,
					front_rise: 9,
					thigh: 10,
					knee: 7.75,
					leg_opening: 7.5,
					inseam: 33,
				   color: "Indigo",
				   fabric_origin: "Kurabo Mills",
				   made_in: "USA",
				   denim_weight: 15,
				   sanforized: true,
				   stretch: false,
				   selvedge: true,
				   price: "265.00",
				   link: "http://www.blueowl.us/product/baldwin-denim-the-samuel-15oz-kurabo-selvedge-denim-in-indigo/")

	Item.create!(name: "The Samuel",
				   brand: "Baldwin",
					tag_size: 29,
					waist: 30.5,
					front_rise: 9,
					thigh: 10.5,
					knee: 8,
					leg_opening: 7.75,
					inseam: 33,
				   color: "Indigo",
				   fabric_origin: "Kurabo Mills",
				   made_in: "USA",
				   denim_weight: 15,
				   sanforized: true,
				   stretch: false,
				   selvedge: true,
				   price: "265.00",
				   link: "http://www.blueowl.us/product/baldwin-denim-the-samuel-15oz-kurabo-selvedge-denim-in-indigo/")

	Item.create!(name: "The Samuel",
				   brand: "Baldwin",
					tag_size: 30,
					waist: 32,
					front_rise: 9.25,
					thigh: 10.75,
					knee: 8.25,
					leg_opening: 8,
					inseam: 33.5,
				   color: "Indigo",
				   fabric_origin: "Kurabo Mills",
				   made_in: "USA",
				   denim_weight: 15,
				   sanforized: true,
				   stretch: false,
				   selvedge: true,
				   price: "265.00",
				   link: "http://www.blueowl.us/product/baldwin-denim-the-samuel-15oz-kurabo-selvedge-denim-in-indigo/")

	Item.create!(name: "The Samuel",
				   brand: "Baldwin",
					tag_size: 31,
					waist: 33,
					front_rise: 9.5,
					thigh: 11,
					knee: 8.25,
					leg_opening: 8,
					inseam: 35.5,
				   color: "Indigo",
				   fabric_origin: "Kurabo Mills",
				   made_in: "USA",
				   denim_weight: 15,
				   sanforized: true,
				   stretch: false,
				   selvedge: true,
				   price: "265.00",
				   link: "http://www.blueowl.us/product/baldwin-denim-the-samuel-15oz-kurabo-selvedge-denim-in-indigo/")

	Item.create!(name: "The Samuel",
				   brand: "Baldwin",
					tag_size: 32,
					waist: 34,
					front_rise: 9.75,
					thigh: 11.4,
					knee: 8.4,
					leg_opening: 8,
					inseam: 34,
				   color: "Indigo",
				   fabric_origin: "Kurabo Mills",
				   made_in: "USA",
				   denim_weight: 15,
				   sanforized: true,
				   stretch: false,
				   selvedge: true,
				   price: "265.00",
				   link: "http://www.blueowl.us/product/baldwin-denim-the-samuel-15oz-kurabo-selvedge-denim-in-indigo/")

	Item.create!(name: "The Samuel",
				   brand: "Baldwin",
					tag_size: 33,
					waist: 34.5,
					front_rise: 10,
					thigh: 11.75,
					knee: 8.7,
					leg_opening: 8.1,
					inseam: 34,
				   color: "Indigo",
				   fabric_origin: "Kurabo Mills",
				   made_in: "USA",
				   denim_weight: 15,
				   sanforized: true,
				   stretch: false,
				   selvedge: true,
				   price: "265.00",
				   link: "http://www.blueowl.us/product/baldwin-denim-the-samuel-15oz-kurabo-selvedge-denim-in-indigo/")

	Item.create!(name: "The Samuel",
				   brand: "Baldwin",
					tag_size: 34,
					waist: 35.5,
					front_rise: 10.25,
					thigh: 12,
					knee: 8.9,
					leg_opening: 8.35,
					inseam: 34,
				   color: "Indigo",
				   fabric_origin: "Kurabo Mills",
				   made_in: "USA",
				   denim_weight: 15,
				   sanforized: true,
				   stretch: false,
				   selvedge: true,
				   price: "265.00",
				   link: "http://www.blueowl.us/product/baldwin-denim-the-samuel-15oz-kurabo-selvedge-denim-in-indigo/")

	Item.create!(name: "The Samuel",
				   brand: "Baldwin",
					tag_size: 36,
					waist: 37,
					front_rise: 10.75,
					thigh: 12.5,
					knee: 9.5,
					leg_opening: 8.5,
					inseam: 34,
				   color: "Indigo",
				   fabric_origin: "Kurabo Mills",
				   made_in: "USA",
				   denim_weight: 15,
				   sanforized: true,
				   stretch: false,
				   selvedge: true,
				   price: "265.00",
				   link: "http://www.blueowl.us/product/baldwin-denim-the-samuel-15oz-kurabo-selvedge-denim-in-indigo/")

#Eternal 811-------------------------------------------------

	# Item.create!(name: "811",
	# 			   brand: "Eternal",

	# 			   color: "Indigo",
	# 			   fabric_origin: "Japan",
	# 			   made_in: "Japan",
	# 			   denim_weight: 14.5,
	# 			   sanforized: true,
	# 			   stretch: false,
	# 			   selvedge: true,
	# 			   price: "275.00",
	# 			   link: "http://www.blueowl.us/product/eternal-145oz-slim-straight-raw-selvedge-denim-model-811/")

#------------------------------------------------------------
	# Item.create!(name: "",
	# 			   brand: "",
	# 				tag_size: ,
	# 				waist: ,
	# 				front_rise: ,
	# 				thigh: ,
	# 				knee: ,
	# 				leg_opening: ,
	# 				inseam: ,
	# 			   color: "",
	# 			   fabric_origin: "",
	# 			   made_in: "",
	# 			   denim_weight: ,
	# 			   sanforized: ,
	# 			   stretch: ,
	# 			   selvedge: ,
	# 			   price: "",
	# 			   link: "")
end