namespace :db do
  desc "Fill database with jeans"
  task populate: :environment do
    make_items
  end
end

def make_items
	Item.create!(name: "SL-100x",
				   brand: "3sixteen",
				   tag_size: 28,
				   waist: 29,
				   front_rise: 10.3,
				   thigh: 10.7,
				   knee: 8.2,
				   leg_opening: 7.3,
				   color: "Indigo",
				   denim_weight: 14.5,
				   inseam: 37,
				   sanforized: true,
				   price: "215.00",
				   link: "http://www.selfedge.com/shop/index.php?main_page=product_info&cPath=82&products_id=438")

	Item.create!(name: "SL-100x",
				   brand: "3sixteen",
				   tag_size: 29,
				   waist: 30,
				   front_rise: 10.4,
				   thigh: 11.0,
				   knee: 8.3,
				   leg_opening: 7.5,
				   inseam: 37,
				   color: "Indigo",
				   denim_weight: 14.5,
				   sanforized: true,
				   price: "215.00",
				   link: "http://www.selfedge.com/shop/index.php?main_page=product_info&cPath=82&products_id=438")

	Item.create!(name: "SL-100x",
				   brand: "3sixteen",
				   tag_size: 30,
				   waist: 31,
				   front_rise: 10.8,
				   thigh: 11.2,
				   knee: 8.3,
				   leg_opening: 7.7,
				   inseam: 37,
				   color: "Indigo",
				   denim_weight: 14.5,
				   sanforized: true,
				   price: "215.00",
				   link: "http://www.selfedge.com/shop/index.php?main_page=product_info&cPath=82&products_id=438")

	Item.create!(name: "SL-100x",
				   brand: "3sixteen",
				   tag_size: 31,
				   waist: 32,
				   front_rise: 11,
				   thigh: 11.3,
				   knee: 8.4,
				   leg_opening: 7.8,
				   inseam: 37,
				   color: "Indigo",
				   denim_weight: 14.5,
				   sanforized: true,
				   price: "215.00",
				   link: "http://www.selfedge.com/shop/index.php?main_page=product_info&cPath=82&products_id=438")

	Item.create!(name: "SL-100x",
				   brand: "3sixteen",
				   tag_size: 32,
				   waist: 33,
				   front_rise: 11.1,
				   thigh: 11.7,
				   knee: 8.7,
				   leg_opening: 7.9,
				   inseam: 37,
				   color: "Indigo",
				   denim_weight: 14.5,
				   sanforized: true,
				   price: "215.00",
				   link: "http://www.selfedge.com/shop/index.php?main_page=product_info&cPath=82&products_id=438")

	Item.create!(name: "SL-100x",
				   brand: "3sixteen",
				   tag_size: 33,
				   waist: 34,
				   front_rise: 11.3,
				   thigh: 12,
				   knee: 8.8,
				   leg_opening: 8,
				   inseam: 37,
				   color: "Indigo",
				   denim_weight: 14.5,
				   sanforized: true,
				   price: "215.00",
				   link: "http://www.selfedge.com/shop/index.php?main_page=product_info&cPath=82&products_id=438")
	
	Item.create!(name: "SL-100x",
				   brand: "3sixteen",
				   tag_size: 34,
				   waist: 35,
				   front_rise: 11.7,
				   thigh: 12.3,
				   knee: 9.1,
				   leg_opening: 8.2,
				   inseam: 37,
				   color: "Indigo",
				   denim_weight: 14.5,
				   sanforized: true,
				   price: "215.00",
				   link: "http://www.selfedge.com/shop/index.php?main_page=product_info&cPath=82&products_id=438")

	Item.create!(name: "SL-100x",
				   brand: "3sixteen",
				   tag_size: 36,
				   waist: 37,
				   front_rise: 12.1,
				   thigh: 12.7,
				   knee: 9.5,
				   leg_opening: 8.6,
				   inseam: 37,
				   color: "Indigo",
				   denim_weight: 14.5,
				   sanforized: true,
				   price: "215.00",
				   link: "http://www.selfedge.com/shop/index.php?main_page=product_info&cPath=82&products_id=438")

	Item.create!(name: "SL-100x",
				   brand: "3sixteen",
				   tag_size: 38,
				   waist: 39,
				   front_rise: 12.3,
				   thigh: 13,
				   knee: 9.5,
				   leg_opening: 9,
				   inseam: 37,
				   color: "Indigo",
				   denim_weight: 14.5,
				   sanforized: true,
				   price: "215.00",
				   link: "http://www.selfedge.com/shop/index.php?main_page=product_info&cPath=82&products_id=438")

	Item.create!(name: "SL-100x",
				   brand: "3sixteen",
				   tag_size: 40,
				   waist: 41,
				   front_rise: 12.5,
				   thigh: 14,
				   knee: 9.8,
				   leg_opening: 9.1,
				   inseam: 37,
				   color: "Indigo",
				   denim_weight: 14.5,
				   sanforized: true,
				   price: "215.00",
				   link: "http://www.selfedge.com/shop/index.php?main_page=product_info&cPath=82&products_id=438")

	Item.create!(name: "Stanton 14.5oz",
				   brand: "Rogue Territory",
				   tag_size: 26,
				   waist: 28.5,
				   front_rise: 9.75,
				   thigh: 10.5,
				   knee: 7,
				   leg_opening: 6.5,
				   inseam: 36,
				   color: "Indigo",
				   denim_weight: 14.5,
				   sanforized: true,
				   price: "210.00",
				   link: "http://www.selfedge.com/shop/index.php?main_page=product_info&cPath=82&products_id=438")

	Item.create!(name: "Stanton 14.5oz",
				   brand: "Rogue Territory",
				   tag_size: 27,
				   waist: 29.5,
				   front_rise: 9.75,
				   thigh: 11,
				   knee: 7.25,
				   leg_opening: 6.75,
				   inseam: 36,
				   color: "Indigo",
				   denim_weight: 14.5,
				   sanforized: true,
				   price: "210.00",
				   link: "http://www.selfedge.com/shop/index.php?main_page=product_info&cPath=82&products_id=438")

	Item.create!(name: "Stanton 14.5oz",
				   brand: "Rogue Territory",
				   tag_size: 28,
				   waist: 30.5,
				   front_rise: 10,
				   thigh: 11.25,
				   knee: 7.5,
				   leg_opening: 7,
				   inseam: 36,
				   color: "Indigo",
				   denim_weight: 14.5,
				   sanforized: true,
				   price: "210.00",
				   link: "http://www.selfedge.com/shop/index.php?main_page=product_info&cPath=82&products_id=438")

	Item.create!(name: "Stanton 14.5oz",
				   brand: "Rogue Territory",
				   tag_size: 29,
				   waist: 31.5,
				   front_rise: 10.25,
				   thigh: 11.5,
				   knee: 8,
				   leg_opening: 7.5,
				   inseam: 36,
				   color: "Indigo",
				   denim_weight: 14.5,
				   sanforized: true,
				   price: "210.00",
				   link: "http://www.selfedge.com/shop/index.php?main_page=product_info&cPath=82&products_id=438")

	Item.create!(name: "Stanton 14.5oz",
				   brand: "Rogue Territory",
				   tag_size: 30,
				   waist: 32.5,
				   front_rise: 10.25,
				   thigh: 11.75,
				   knee: 8.25,
				   leg_opening: 7.75,
				   inseam: 36,
				   color: "Indigo",
				   denim_weight: 14.5,
				   sanforized: true,
				   price: "210.00",
				   link: "http://www.selfedge.com/shop/index.php?main_page=product_info&cPath=82&products_id=438")

	Item.create!(name: "Stanton 14.5oz",
				   brand: "Rogue Territory",
				   tag_size: 31,
				   waist: 33.5,
				   front_rise: 10.5,
				   thigh: 12,
				   knee: 8.5,
				   leg_opening: 8,
				   inseam: 36,
				   color: "Indigo",
				   denim_weight: 14.5,
				   sanforized: true,
				   price: "210.00",
				   link: "http://www.selfedge.com/shop/index.php?main_page=product_info&cPath=82&products_id=438")

	Item.create!(name: "Stanton 14.5oz",
				   brand: "Rogue Territory",
				   tag_size: 32,
				   waist: 34.5,
				   front_rise: 10.5,
				   thigh: 12.5,
				   knee: 8.75,
				   leg_opening: 8.25,
				   inseam: 36,
				   color: "Indigo",
				   denim_weight: 14.5,
				   sanforized: true,
				   price: "210.00",
				   link: "http://www.selfedge.com/shop/index.php?main_page=product_info&cPath=82&products_id=438")

	Item.create!(name: "Stanton 14.5oz",
				   brand: "Rogue Territory",
				   tag_size: 33,
				   waist: 35.5,
				   front_rise: 10.75,
				   thigh: 12.75,
				   knee: 9,
				   leg_opening: 8.5,
				   inseam: 36,
				   color: "Indigo",
				   denim_weight: 14.5,
				   sanforized: true,
				   price: "210.00",
				   link: "http://www.selfedge.com/shop/index.php?main_page=product_info&cPath=82&products_id=438")

	Item.create!(name: "Stanton 14.5oz",
				   brand: "Rogue Territory",
				   tag_size: 34,
				   waist: 36.5,
				   front_rise: 11,
				   thigh: 13,
				   knee: 9.25,
				   leg_opening: 8.75,
				   inseam: 36,
				   color: "Indigo",
				   denim_weight: 14.5,
				   sanforized: true,
				   price: "210.00",
				   link: "http://www.selfedge.com/shop/index.php?main_page=product_info&cPath=82&products_id=438")

	Item.create!(name: "Stanton 14.5oz",
				   brand: "Rogue Territory",
				   tag_size: 36,
				   waist: 38.5,
				   front_rise: 11.25,
				   thigh: 13.5,
				   knee: 9.75,
				   leg_opening: 9,
				   inseam: 36,
				   color: "Indigo",
				   denim_weight: 14.5,
				   sanforized: true,
				   price: "210.00",
				   link: "http://www.selfedge.com/shop/index.php?main_page=product_info&cPath=82&products_id=438")

	Item.create!(name: "Stanton 14.5oz",
				   brand: "Rogue Territory",
				   tag_size: 38,
				   waist: 40.5,
				   front_rise: 11.25,
				   thigh: 15,
				   knee: 10,
				   leg_opening: 9.25,
				   inseam: 36,
				   color: "Indigo",
				   denim_weight: 14.5,
				   sanforized: true,
				   price: "210.00",
				   link: "http://www.selfedge.com/shop/index.php?main_page=product_info&cPath=82&products_id=438")
end
